### ISSUE TITLE
Not enough arguments for format string

### ISSUE THREAD

**Issue by davenlin19** [JazzCore/python-pdfkit#100]
I have the following problem with the library while running with apache2:

```
File "/python2.7/site-packages/pdfkit/pdfkit.py" in to_pdf
181.                               '%s ' %(' '.join(args)),e)

Exception Type: TypeError at /api/create_order/
Exception Value: not enough arguments for format string
```

But it works with Django in dev mode:
```
service apache2 stop
python manage.py runserver
```

Thanks !

**Comment by jayeshsingh9767** [comment]
I am also facing same issue...

**Comment by JazzCore** [comment]
Closing due to date, feel free to reopen if you need ping me about this issue.

Sorry that it took so long for me to get to it...

**Comment by OmarFlow** [comment]
@JazzCore encountered the same problem, how can it be solved?

**Comment by TheNiteCoder** [comment]
My issue I think was the directory wasn't created and so it failed. When I created the directory for pdf, it worked fine.

**Comment by MareSeestern** [comment]
> My issue I think was the directory wasn't created and so it failed. When I created the directory for pdf, it worked fine.

I agree with @TheNiteCoder . In my case, the directory existed, but I messed up the access rights.
