### ISSUE TITLE
Missing  contents in PDF.

### ISSUE THREAD

**Issue by navdeepghai1** [JazzCore/python-pdfkit#103]
## In HTML format I am able to see all the contents but It's not showing correctly after converting HTML contents to PDF.

**Contents in HTML:**
```
Below is the HTML code which I am using for title:
 <p id="toc" style="font-size:18px;text-align:left;"><b><ul>TABLE OF CONTENTS </ul></b></p>
```
![screen shot 2018-05-22 at 9 10 35 am](https://user-images.githubusercontent.com/30634335/40343297-40fdc924-5da0-11e8-869b-95aa977c1011.png)
>----------------------------------------------------------------------------------
**Contents in PDF:**
> In PDF some text is missing, I don't know how to fix it.
``` 
Below is the HTML code which I am using for title:
 <p id="toc" style="font-size:18px;text-align:left;"><b><ul>TABLE OF CONTENTS</ul></b></p>
```
![screen shot 2018-05-22 at 9 10 22 am](https://user-images.githubusercontent.com/30634335/40343310-4aa51d74-5da0-11e8-9345-18d977e465f9.png)

**Comment by vikashsrivastava1111989** [comment]
Hi Navdeep,

It woulb be great if you will little elaborate your issue. 
Are you saying about image load issue? or 
alignment issue? 
in generated PDF

**Comment by navdeepghai1** [comment]
Yes, It's about alignment issue.

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
