### ISSUE TITLE
how to use it in google app engine

### ISSUE THREAD

**Issue by manzanofab** [JazzCore/python-pdfkit#108]
Hi have deploy my first app in app engine, but i get an error when trying to create the pdf

are there any instructions on how to install in app engine?

Django Version: | 2.0.7
Exception Type: OSError
Exception Value: No wkhtmltopdf executable found: "b''" If this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf
Exception Location: /env/lib/python3.6/site-packages/pdfkit/configuration.py in __init__, line 27
Python Executable: /env/bin/python3.6

**Comment by adelewyr** [comment]
Perhaps it's because you do not install wkhtmltopdf ?

**Comment by AcckiyGerman** [comment]
Sure you can't install it on the GAE.
Try to use https://www.sejda.com/html-to-pdf , they have an API.

**Comment by vikashsrivastava1111989** [comment]
Hi manzanofab,

Better you can use AWS lambda or install the wkhtmltopdf on EC2 free tier instance. 


Thanks

**Comment by AcckiyGerman** [comment]
~~Try to use [WeasyPrint](https://weasyprint.org/)~~ oh wait, it has some [binary dependencies](https://weasyprint.readthedocs.io/en/stable/install.html#linux), too :(

**Comment by JazzCore** [comment]
Closing, since its a wkhtmltopdf issue.
