### ISSUE TITLE
Table of Content get blank page 

### ISSUE THREAD

**Issue by tuanklnew** [JazzCore/python-pdfkit#113]
I am working with python-pdfkit to genterate report automatically. In my report, I have cover, table of contents. So my code is:

>MARGIN = '0.5in'
> css = ['bootstrap.min.css']
> options = {
>     # 'quiet': '',
>     'page-size': 'A4',
>     'margin-top': MARGIN,
>     'margin-right': MARGIN,
>     'margin-bottom': MARGIN,
>     'margin-left': MARGIN,
>     'disable-smart-shrinking': '',
>     'footer-right': 'Page [page]',
>     'header-right': '[section]',
>     'header-line':'',
>     'footer-line':''
>    }
> toc = {
>     'xsl-style-sheet': 'toc.xsl'
> }
> pdfkit.from_string(html.read().decode(), 'output.pdf', configuration=config, css=css, cover='firstpage.html', toc=toc, cover_first=True, options=options)

With toc.xsl is default file that I dump from wkhtmltopdf. But TOC page is bank. So I decide to test another case by set **toc argument to ""**

> pdfkit.from_string(html.read().decode(), 'output.pdf', configuration=config, css=css, cover='firstpage.html', toc='', cover_first=True, options=options)

But then I got nothing with TOC. TOC is not existed on my report.

**Comment by Danny5487401** [comment]
i wanna get the solution, too

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
