### ISSUE TITLE
Suppress console logging

### ISSUE THREAD

**Issue by kevinyjiang** [JazzCore/python-pdfkit#115]
Is there any way to suppress the console info logs? Forgive me if the answer can be found somewhere, but I can't seem to find any docs.

```
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

**Comment by avagut** [comment]
From the ReadMe, please pass in as part of the options dictionary parameter the quiet key as below
```
options = { 'quiet': '' }
pdfkit.from_url('google.com', 'out.pdf', options=options)
```
