### ISSUE TITLE
--replace implementation 

### ISSUE THREAD

**Issue by joemillington** [JazzCore/python-pdfkit#116]
What's the correct implementation for --replace:
      --replace <name> <value>        Replace [name] with value in header and footer (repeatable)

My Python code is:

options = { 'header-html': header_html,
                   'footer-html': footer_html,
                   'replace': [
                       ('placeholder_A', 'string A'),
                   ], }

HTML html snippet:
              <div class = title>{{placeholder_A}}</div>

**Comment by JazzCore** [comment]
This seems like a wkhtmltopdf question to me, closing
