### ISSUE TITLE
Correct way to check for wkhtmltopdf installed?

### ISSUE THREAD

**Issue by andymcarter** [JazzCore/python-pdfkit#127]
What is the appropriate way to check for the presence of wkhtmltopdf on a user's system? I have been calling `pdfkit.configuration()`, catching any IOErrors, printing a message directing the user to the appropriate download page. In this case, I need to specify a particular version of wkhtmltopdf, otherwise I would simply reraise the original IOError.

Is this the correct way of using pdfkit to check if wkhtmltopdf is installed?

**Comment by JazzCore** [comment]
Currently there is no way to check if wkhtmltopdf is installed before running conversion methods, I'll make one

**Comment by JazzCore** [comment]
Actually I'm wrong, you can check if wkhtmltopdf is installed:

```python
try:
  config = pdfkit.configuration()
except OSError:
  #not present in PATH
```

So closing this for now.
