### ISSUE TITLE
Change browser

### ISSUE THREAD

**Issue by max-zorn** [JazzCore/python-pdfkit#129]
Hi! I'm trying to make a screenshot of the page from google.sheets, but I get an error that the browser is not supported. Is it possible to change the browser or its version through the options?

script was running on mac os, python version 2.7.15:
```
import imgkit

options = {
	'format': 'png',
	'javascript-delay': '50000',
	}

imgkit.from_url('https://docs.google.com/spreadsheets/d/1tU7Hqk8VtuEM3Pj1T4pKY-4dAuiO-Lkh6N4kStJGAxY/edit#gid=1391628855', 'ermac.jpg', options=options)
```

**Comment by JazzCore** [comment]
wkhtmltoimage is not supported, sorry
