### ISSUE TITLE
wkhtmltopdf exited with non-zero code -9

### ISSUE THREAD

**Issue by singhravi1** [JazzCore/python-pdfkit#132]
Hi Guys, i'm using wkhtmltox_0.12.5-1.bionic_amd64.deb with latest pdfkit.

i'm creating pdf in a docker container with memory limit of 300 MB.
On some tasks, i'm getting the following error,
`OSError: wkhtmltopdf exited with non-zero code -9. error: Loading pages (1/6) [> ] 0% [======> ] 10% [==========> ] 17% [============> ] 20% [=============> ] 23% [===============> ] 25% [=================> ] 29% [===================> ] 32% [=====================> ] 35% [======================> ] 38% [========================> ] 41% [==========================> ] 44% [===========================> ] 46% [============================> ] 48% [=====================================================> ] 89% [============================================================] 100% Counting pages (2/6) [============================================================] Object 1 of 1 Resolving links (4/6) [============================================================] Object 1 of 1 Loading headers and footers (5/6) Printing pages (6/6) [> ] Preparing [============================================================] Page 1 of 1
`
**OS information**
ubuntu 18.04 (docker image)

**How to reproduce**

> I think maybe this is because of an image of large size (in my case it was 5.2 MB)

Create a pdf from html (using pdfkit.from_string() function).
Html contains Two image fields with href to image link (with image size more than 5 MB) and two input fields.
Run the task to create pdf within the container. Put memory limit on the container to 300 MB.

I think it is because of memory outage for my docker container
Is it? What do you guys think?

**Comment by ns-sahin** [comment]
same here

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
