### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by abhimk** [JazzCore/python-pdfkit#133]
Caught an error while generating pdf from HTML using PdfKit latest version (0.6.1) and wkhtmltox-0.12.5-1.centos7.x86_64.rpm. Please see the attachment.

[Code]
rendered = render_template('mod_feedback/grievance-report-template.html',report_title=report_header,grievance_registered=grievance_regd)
pdf_content = pdfkit.from_string(str(rendered), False)
response = make_response(pdf_content)
response.headers['Content-Type'] = 'application/pdf'
response.headers['Content-Disposition'] = 'attachment; filename=%s.pdf' % report_header

This is the code that I used for generating pdf. Its working fine with my development machine. But showing the error **OSError: [Errno 2] No such file or directory** when running the same in production server.
[stack-trace-no-such-directory.txt](https://github.com/JazzCore/python-pdfkit/files/3067633/stack-trace-no-such-directory.txt)

Development Machine OS - Windows 10

Production Server - OS - Centos 7

The application is developed by using Python Flask.

Does anyone have any idea? How to fix this issue?

**Comment by lukojewel** [comment]
Having the same issue here. 
`[Errno 2] No such file or directory: 'which': 'which'`

Working fine in local (ubuntu). But doesnt work on ec2 ubuntu instance.

Python version: 3.6.9

**Comment by InzamamAnwar** [comment]
Got the same error while executing through python on AWS EC2. Anyone found solution to this problem.

**Comment by sscotti** [comment]
Not really sure.  I have it running on UBUNTU.  Maybe you should check where the binary is installed and that your PATH ENV includes that.  Sounds like Python can't locate the binary.  Might be expecting /usr/local/bin or /usr/bin, etc.

**Comment by InzamamAnwar** [comment]
I have successfully used `pdfkit` in production environment (Flask app/Nginx Server on AWS EC2). I would suggest to not install it from `apt-get` and follow this [script](https://github.com/JazzCore/python-pdfkit/blob/master/travis/before-script.sh) and then use configuration. I have used following configuration
```
config = pdfkit.configuration(wkhtmltopdf=bytes('/usr/bin/wkhtmltopdf', 'utf-8'))
```

**Comment by Hikaon** [comment]
@lukojewel this is actually error `No wkhtmltopdf executable found: "%s"\n'`
you can fix it by directly set configuration parameters like this 
```
    config = pdfkit.configuration(wkhtmltopdf=bytes('/opt/bin/wkhtmltopdf', 'utf-8'))
    pdf = pdfkit.from_string(rendered_page, False, configuration=config)
```

tested on AWS Lambda

**Comment by JazzCore** [comment]
I've added checks for ``where`` and ``which`` that are used to get wkhtmltopdf path, on some machines they are missing for some reason. If pdfkit cant find wkhtmltopdf in ``PATH`` you should use ``pdfkit.configuration()`` calls to provide a path to binary
