### ISSUE TITLE
Release of a new version on PyPi

### ISSUE THREAD

**Issue by mzonzon** [JazzCore/python-pdfkit#135]
Is the release of a new version planned soon?

**Comment by mrandrewandrade** [comment]
Similar for conda-forge: https://anaconda.org/conda-forge/python-pdfkit

Seems to be over 1 year old

**Comment by mrandrewandrade** [comment]
@JazzCore Happy to help make this work for conda

**Comment by fmarco** [comment]
any news :/ ?

**Comment by JazzCore** [comment]
I'll make a new release on PyPI in a few days, sorry that it took so long...
