### ISSUE TITLE
How to set the title of the generated pdf

### ISSUE THREAD

**Issue by dinukadesilva** [JazzCore/python-pdfkit#138]
I tried following approaches and didn't work.

1. Set the title tag in the html file
2. Added `<meta name="pdfkit-title" content="ABCD"/>`
3. Passed the "title" via options

Any help is much appreciated.

**Comment by vikashsrivastava1111989** [comment]
Hi dinukadesilva,

I am not sure by what function you are creating the PDF using pdfkit package.

In my case I am using from_string() function available in pdfkit package.

You need to simply use it as explained below:

1. create your option first
for e.g options = {
    'title': 'My Custom Title Goes Here',
    'page-size': 'Letter',
    'margin-top': '0in',
    'margin-right': '0in',
    'margin-bottom': '0in',
    'margin-left': '0in',
    'encoding': "UTF-8",
    'no-outline': None
}
# pdf scontent in the format of html string 
pdf_content = '<html><body>Hi This is a dummy example</html>'

# created the pdf object
pdfOBJ = pdfkit.from_string(pdf_content, False, options)

And finally write pdfOBJ to the respective location on your disk where you want by write function. If you will open the pdf you will get the title of the pdf which you can see by going in FILES>Properties>Description inside pdf acrobat application.

Hope above works for you

Thanks,

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
