### ISSUE TITLE
cookie value is empty string cause AssertionError

### ISSUE THREAD

**Issue by mengyyy** [JazzCore/python-pdfkit#140]
I get this error when i generate pdf with cookies
`AssertionError: Option value can only be either a string or a (tuple, list) of 2 items`
And i found the reason is one of my cookies is `('_ntv_uid', '')` which value is `''`
I think it is better to mark it in the document.

**Comment by JazzCore** [comment]
You should use ``""`` as value for empty cookies, like this: ``('_ntv_uid', '""')``, closing.

Sorry that it took so long for me to get to it...
