### ISSUE TITLE
Inconsistent style of table.

### ISSUE THREAD

**Issue by HanDuwol** [JazzCore/python-pdfkit#142]
I converted the table to PDF with a simple example.
But is the table's style broken because of UTF-8?

<html>
<table class="blueTable" border="1" cellspacing="0" cellpadding="0" style="border-collapse:collapse;border:none;width: 100%;">
 <thead style="font-weight:bold;">
 <tr>
 <td align="center" style="height:35px">
 <p class="table_common_font" align="center">
 <span class="table_head1">Date</span>
 </p>
 </td>
 <td align="center">
 <p class="table_common_font" align="center">
 <span class="table_head1">Object</span>
 </p>
 </td>
 <td align="center">
 <p class="table_common_font" align="center">
 <span class="table_head1">최접근거리(LD)</span>
 </p>
 </td>
 <td align="center">
 <p class="table_common_font" align="center">
 <span class="table_head1">예상크기</span>
 </p>
 </td>
 <td align="center">
 <p class="table_common_font" align="center">
 <span class="table_head1">상대속도(km/s)</span>
 </p>
 </td>
 </tr>
 </thead>
 <tbody id="near_earth">
 <tr>
<td style="height:20px">
 <p class="table_common_font" align="center">
 <span class="table_body1" style="font-size: 13px;">2019-Sep-01</span>
 </p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 FV2</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">20.84</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">26 m -   58 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2.19</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-02</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 QA5</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">5.56</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">16 m -   35 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">13.53</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-02</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 QX1</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">18.71</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">23 m -   51 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">16.84</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-03</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 OF2</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">18.08</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">40 m -   89 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">10.73</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-03</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 QU1</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">29.27</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">47 m -  110 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">12.76</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-03</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2018 DE1</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">11.05</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">21 m -   47 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">6.57</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-04</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 QX3</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">10.97</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">24 m -   54 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">17.82</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-04</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2006 SE6</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">27.95</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">73 m -  160 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">6.85</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-05</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 QE1</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">12.88</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">25 m -   56 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">6.63</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-06</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 GT3</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">19.44</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">160 m -  370 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">13.64</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-06</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2009 EK1</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">22.25</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">140 m -  310 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">7.18</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-07</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2016 LT1</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">28.15</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">4.2 m -  9.4 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">6.10</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-08</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 QZ</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">15.55</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">16 m -   35 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">4.34</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-09</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 QZ3</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">9.65</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">29 m -   66 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">7.47</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-10</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 QY4</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2.47</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">6.9 m -   15 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">7.78</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-10</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2005 RB3</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">19.82</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">80 m -  180 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">20.42</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-12</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 RX2</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">7.15</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">5.6 m -   12 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">5.34</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-12</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 RJ1</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">10.69</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">11 m -   25 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">10.45</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-13</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2010 RM82</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">1.63</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">18 m -   39 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">14.58</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-13</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2013 CV83</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">16.09</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">46 m -  100 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">13.12</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-14</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2010 CO1</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">13.86</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">120 m -  260 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">14.36</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-14</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 RT</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">13.52</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">36 m -   81 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">16.64</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-14</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 QT2</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">22.36</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">45 m -  100 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">14.34</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-14</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 RQ2</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">9.26</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">23 m -   51 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">17.17</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-14</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2000 QW7</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">13.87</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">290 m -  650 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">6.42</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-16</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 JF1</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">11.16</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">46 m -  100 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">4.30</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-16</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2018 FU1</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">18.33</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">12 m -   26 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">4.70</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-16</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 RC</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">17.26</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">120 m -  260 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">15.08</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-17</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2015 PK57</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">21.10</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">31 m -   68 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">9.70</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-17</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 QO5</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">25.29</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">47 m -  100 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">10.63</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-20</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2000 SP43</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">26.59</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">530 m -  1.2 km</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">15.60</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-20</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 RV</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">22.07</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">49 m -  110 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">17.03</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-20</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 RP2</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">8.34</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">4.3 m -  9.7 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">1.57</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-21</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2017 SL16</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">7.89</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">18 m -   41 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">6.47</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-21</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2017 SM21</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">3.18</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">15 m -   33 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">9.61</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-21</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 RE2</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">19.30</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">28 m -   64 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">8.71</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-21</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 RB3</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">18.81</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">38 m -   85 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">11.84</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-22</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 QZ1</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">12.32</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">57 m -  130 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">8.19</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-23</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2007 TQ24</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">23.98</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">100 m -  230 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">13.95</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-24</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">1998 FF14</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">10.82</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">190 m -  430 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">22.26</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-26</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019 QY3</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">13.85</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">31 m -   69 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">8.38</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-26</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2017 KP27</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">4.22</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">18 m -   41 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">4.71</span>
</p>
</td>
</tr>
<tr>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2019-Sep-27</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">2006 QV89</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">18.02</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">23 m -   52 m</span>
</p>
</td>
<td style="height:20px">
<p class="table_common_font" align="center">
<span class="table_body1" style="font-size: 13px;">4.13</span>
</p>
</td>
</tr>
</tbody>
 </table>
</html>

![image](https://user-images.githubusercontent.com/39490993/64941957-df0d4080-d8a2-11e9-93e7-65d11e12ab37.png)

**Comment by lifez** [comment]
Happened with me too

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
