### ISSUE TITLE
wkhtmltopdf (12.4) exited with incorrect location for margin-left

### ISSUE THREAD

**Issue by mafiosso** [JazzCore/python-pdfkit#143]
**Pdfkit prints:** 
wkhtmltopdf exited with non-zero code 1. error:
--margin-left specified in incorrect location

Name:
  wkhtmltopdf 0.12.4 (with patched qt)

**Input options given (same behavior with dict):**
```
options = OrderedDict([
            ('page-size', 'A4'),
            ('encoding', "UTF-8"),
            ('margin-top', '0.75in'),
            ('margin-bottom', '0.75in'),
            ('margin-left', '0.75in'),
            ('margin-right', '0.75in'),
            ('cookie', ("DP_logged_id", cookie_value)),
        ])
```

**Comment by JazzCore** [comment]
Cant reproduce, please provide a full test case if you still interested :)

Also note that --cookies are currently not supported.

Feel fee to reopen if needed
