### ISSUE TITLE
OSError: [Errno 86] Bad CPU type in executable

### ISSUE THREAD

**Issue by nmvasani** [JazzCore/python-pdfkit#147]
Since OSX Catalina was introduced, and 32-bit processes are NOT supported ----> PDFKit's use of subprocess means PDFKit no longer is operational.

The following error is received:
OSError: [Errno 86] Bad CPU type in executable 

Any plans to remove subprocess completely...perhaps use threading or multiprocess?
Or perhaps don't sub process at all?

Any other workarounds would be much appreciated.

**Comment by nmvasani** [comment]
Any other workarounds would be much appreciated.

**Comment by JazzCore** [comment]
Not sure if it's still a problem, works good for me on Big Sur. Feel free to reopen if problem still exists
