### ISSUE TITLE
How to uninstall wkhtmltopdf installed by before-script.sh?

### ISSUE THREAD

**Issue by TejasAvinashShetty** [JazzCore/python-pdfkit#148]
Due to #128, I wish to uninstall wkhtmltopdf (installed via [before-script.sh](https://github.com/JazzCore/python-pdfkit/blob/master/travis/before-script.sh))

**Comment by JazzCore** [comment]
Closing due to date, feel free to reopen if you need ping me about this issue.

Sorry that it took so long for me to get to it...
