### ISSUE TITLE
brew cast install wkhtmltopdf installation failed

### ISSUE THREAD

**Issue by NavalKishor** [JazzCore/python-pdfkit#149]
`brew install Caskroom/cask/wkhtmltopdf`

> ==> Tapping caskroom/cask
> Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
> remote: Enumerating objects: 3618, done.
> remote: Counting objects: 100% (3618/3618), done.
> remote: Compressing objects: 100% (3610/3610), done.
> remote: Total 3618 (delta 25), reused 550 (delta 6), pack-reused 0
> Receiving objects: 100% (3618/3618), 1.22 MiB | 1.65 MiB/s, done.
> Resolving deltas: 100% (25/25), done.
> Tapped 1 command and 3506 casks (3,623 files, 3.9MB).
> ==> brew cask install Caskroom/cask/wkhtmltopdf 
> ==> Caveats
> Cask wkhtmltopdf installs files under /usr/local. The presence of such
> files can cause warnings when running `brew doctor`, which is considered
> to be a bug in Homebrew Cask.
> 
> ==> Downloading https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox-0.12.5-1.macos-cocoa.pkg
> 
> curl: (60) SSL certificate problem: certificate has expired
> More details here: https://curl.haxx.se/docs/sslcerts.html
> 
> curl performs SSL certificate verification by default, using a "bundle"
>  of Certificate Authority (CA) public keys (CA certs). If the default
>  bundle file isn't adequate, you can specify an alternate file
>  using the --cacert option.
> If this HTTPS server uses a certificate signed by a CA represented in
>  the bundle, the certificate verification probably failed due to a
>  problem with the certificate (it might be expired, or the name might
>  not match the domain name in the URL).
> If you'd like to turn off curl's verification of the certificate, use
>  the -k (or --insecure) option.
> HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
> Error: Download failed on Cask 'wkhtmltopdf' with message: Download failed: https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox-0.12.5-1.macos-cocoa.pkg
>

**Comment by hcrisgnya** [comment]
I received the following error:
Error: caskroom/cask was moved. Tap homebrew/cask-cask instead.
using this repo fixed the problem
brew cask install homebrew/cask/wkhtmltopdf

**Comment by Lucurus** [comment]
The recommended command to install the cask is (according to brew): `brew cask install wkhtmltopdf `

**Comment by JazzCore** [comment]
Fixed in #173
