### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/content/gdrive/My Drive/Project/wkhtmltopdf.exe'

### ISSUE THREAD

**Issue by 648374hub** [JazzCore/python-pdfkit#150]
Is there any way of using the library wkhtmltopdf in google colab? I keep getting this error and can't find a way to override the permission. Also it can't find the wkhtmltopdf.exe even if i copied it to the path and also tried to pass the path manually through config() already. But still no success. Any help will be great.

**Comment by JazzCore** [comment]
Sorry, no idea, closing
