### ISSUE TITLE
Error:about:blank Exit with code 1 due to network error: ProtocolUnknownError

### ISSUE THREAD

**Issue by enjoyLifeStorm** [JazzCore/python-pdfkit#159]
I have encountered some problems. After the target website is saved as HTML, and then converted into PDF through HTML, the following exception information will appear. According to the source code analysis, the target website is likely to be written by Vue. How to solve this exception.
`Loading pages (1/6)
Warning: Blocked access to file                                   
Warning: Blocked access to file 
Warning: Blocked access to file 
Warning: Blocked access to file 
Warning: Blocked access to file 
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Error: Failed loading page file:///C:/Users/engle/AppData/Local/Temp/wktemp-e9d8eab8-4d10-4b8e-aa3d-188b498c4923.html (sometimes it will work just to ignore this error with --load-error-handling ignore)
Warning: A finished ResourceObject received a loading progress signal. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Exit with code 1 due to network error: ProtocolUnknownError`

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
