### ISSUE TITLE
python pdf generation Asian language issue how to solve it ? 

### ISSUE THREAD

**Issue by paragjp** [JazzCore/python-pdfkit#161]
Hi 

Does pdfkit support asian languages, I am from India, so my question related to languages Hindi and Marathi in python script

I am generating pdf from URL using pdfkit, but it is generating some junk characters in pdf, my code is

```
options = {
'page-size': 'Letter',
'margin-top': '0.75in',
'margin-right': '0.75in',
'margin-bottom': '0.75in',
'margin-left': '0.75in',
'encoding': "UTF-8",
'custom-header' : [('Accept-Encoding', 'gzip')],
'cookie': [
('cookie-name1', 'cookie-value1'),
('cookie-name2', 'cookie-value2'),
],
'no-outline': None
}
import requests
from bs4 import BeautifulSoup
from urllib import request, response, error, parse
from urllib.request import urlopen
import pdfkit
config=pdfkit.configuration(wkhtmltopdf="c:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe")
pdfkit.from_url(URL,'c:\temp\sample.pdf', configuration=config, options=options)

```
and my URL is https://www.loksatta.com/kolhapur-news/politics-on-the-backdrop-of-the-upcoming-elections-of-the-gokul-district-central-co-operative-banks-abn-97-2195442/

Other details are

OS : Win 10 64 bit
pdfkit : 0.6.1

Can you pl help me ?

Thanks 
Parag

**Comment by rjtmehta99** [comment]
Facing somewhat same issue with Japanese characters. The HTML generated has correct characters but when saving it to PDF everything gets distorted.

**Comment by TamaMcGlinn** [comment]
I had this issue today and solved it by calling wkhtmltopdf directly from python code, getting rid of this pdfkit package altogether:

```
import subprocess
subprocess.run(['wkhtmltopdf.exe', '--enable-local-file-access', 'in.html', 'out.pdf'])
```

**Comment by paragjp** [comment]
@TamaMcGlinn 

Thanks for your help and update. But it is still not working for Devnagari font/language used in India.

My code is 

url='https://lokmat.news18.com/national/breaking-news-live-union-consumer-affairs-minister-ram-vilas-paswan-passed-awary-in-delhi-hospital-486046.html'
import subprocess
subprocess.run(['wkhtmltopdf.exe', url, 'c:\\temp\\out.pdf'])

Any other suggestions ?

**Comment by devildani** [comment]
Hi @paragjp, did you solve this issue? I am actually a similar kind of issue with the Burmese characters.

**Comment by paragjp** [comment]
Hi @devildani 

My issue is not solved instead of too much follow up. Pl updated this thread incase you got any solutions.

**Comment by JazzCore** [comment]
Pdfkit by itself supports any languages since it uses unicode in all places, but it cant be said for wkhtmltopdf itself, since when loading pages it does all the work with fonts and text. URL above does not work for me neither from pdfkit neither when run directly from wkhtmltopdf, since issue is on wkhtmltopdf side.

This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...

**Comment by JaimanHemant** [comment]
> 
Did you solve this issue? I am still facing this issue for Japanese characters.
