### ISSUE TITLE
Unable to generate google chart pdf

### ISSUE THREAD

**Issue by mdmohsinali** [JazzCore/python-pdfkit#163]
Hi,

Google charts are missing in the generated PDF file using the following commands. I am using pdfkit version 0.6.1.

$ python3
Python 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdfkit
>>> pdfkit.from_url('https://ncmas.nci.org.au/2020/stats', 'out.pdf')
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                      
True
>>> 

Stay safe.

Mohsin

**Comment by JazzCore** [comment]
Most probably its missing since its loaded dynamically, you can try adding a delay to wkhtmltopdf options or switch to something like a selenium and get page source from it, closing.

Sorry that it took so long for me to get to it...
