### ISSUE TITLE
No wkhtmltopdf executable found.  Issue when starting app in Foreground vs. init.d script

### ISSUE THREAD

**Issue by sscotti** [JazzCore/python-pdfkit#170]
**Not sure if this is an issue with pdfkit per say**.  I'm running a server (Orthanc open source project written in .cpp).  It has a feature that allows for incorporating Python Plug-ins into their framework.  I created a few Python Plug-ins for that, and they all work fine, except the one that uses pdfkit as a wrapper for wkhtmltopdf.  The strange thing is that when I start Orthanc from the CLI int he foreground using a command like:

**`/path/to/orthanc /path/to/config/config.json --verbose`**

wkhtmltopdf works and there is no error.

When I start up from the CLI using an init.d like:

**`/etc/init.d/orthanc (start|stop|restart)`**

my plugin fails with the error:

**"No wkhtmltopdf executable found: \"b''\"\nIf this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf"**

Orthanc starts up either way, and the logs show all plug-ins loading, and the Orthanc Explorer and most of my API also work fine.

The relevant code in the Python script is:  config = pdfkit.configuration(wkhtmltopdf=bytes("/usr/local/bin/wkhtmltopdf", 'utf8'))

My ENV path has:

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

So it seems that it can't find the executable or otherwise does not have permissions when I start up using the init.d script.

The permissions for the executable are 755 and the owner is root.

**Comment by StrikeNP** [comment]
I have a fresh setup running on Mint (Debian) and also have this issue. I also tried manually passing in the config to tell it where wkhtmltopdf is but it still couldn't find it.
`which wkhtmltopdf` returns `/usr/bin/wkhtmltopdf` and passing in neither `/usr/bin/wkhtmltopdf` nor `/usr/bin/` for the path seemed to get pdfkit to work.

**Comment by JazzCore** [comment]
My guess that it got something to do with permissions or venvs, no idea why it cant find binary even with a manually provided path. Reproducible test would be nice, closing for now, feel free to reopen if  you still have this issue.

Sorry that it took so long for me to get to it...
