### ISSUE TITLE
using header-html results in loosing footer details

### ISSUE THREAD

**Issue by irfanharunk** [JazzCore/python-pdfkit#172]
In my Django project, I intend to print a custom header for the pdf using "header-html", while only mentioning the page number in the footer section.
I've used `<!DOCTYPE html>` in both the html files (aaaa.html, my header file and my regular template that needs to be printed)
I've tried passing the header html file as absolute path (in below code ) and also as url of my current project (` http://127.0.0.1:8000/aaaa/ `).

When i don't use header html, i get the footer as usual, but when using header html either as absoulte path or as a url, the header is not printed and the footer is also lost.

            _options = {
                'cookie': [
                    ('csrftoken', options.get('csrftoken','none')),
                    ('sessionid', options.get('session_key','none')),
                ],
                'footer-center': 'Page [page] of [topage]',
                'footer-font-size': '9',
                'header-html': '/var/www/dev-django/myproject/templates/aaaa.html',
            }

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
