### ISSUE TITLE
Small typo in README

### ISSUE THREAD

**Issue by NMO13** [JazzCore/python-pdfkit#177]
I think there is a minor typo:

	options = {
	    'page-size': 'Letter',
	    'margin-top': '0.75in',
	    'margin-right': '0.75in',
	    'margin-bottom': '0.75in',
	    'margin-left': '0.75in',
	    'encoding': "UTF-8",
	    'custom-header' : [
	    	('Accept-Encoding', 'gzip')
	    ]
	    'cookie': [
	    	('cookie-name1', 'cookie-value1'),
	    	('cookie-name2', 'cookie-value2'),
	    ],
	    'no-outline': None
	}

	pdfkit.from_url('http://google.com', 'out.pdf', options=options)

should be

	options = {
	    'page-size': 'Letter',
	    'margin-top': '0.75in',
	    'margin-right': '0.75in',
	    'margin-bottom': '0.75in',
	    'margin-left': '0.75in',
	    'encoding': "UTF-8",
	    'custom-header' : [
	    	('Accept-Encoding', 'gzip')
	    ],
	    'cookie': [
	    	('cookie-name1', 'cookie-value1'),
	    	('cookie-name2', 'cookie-value2'),
	    ],
	    'no-outline': None
	}

	pdfkit.from_url('http://google.com', 'out.pdf', options=options)

**Comment by JazzCore** [comment]
Should be fixed in master, thanks
