### ISSUE TITLE
Output directly to file

### ISSUE THREAD

**Issue by JonasCir** [JazzCore/python-pdfkit#178]
Hi,
it would be great if `api.from_{string, file, url}` could store the result directly in an open file, instead of just taking the `output_path` as argument.

If I'm not mistaken, the only change that is needed would be to modify `pdfkit.to_pdf` and check if the output is a string or an open file (as it is already [done](https://github.com/JazzCore/python-pdfkit/blob/master/pdfkit/pdfkit.py#L169) for `source`)

**Comment by JazzCore** [comment]
Sorry, i see no need implement it since it causes unnecessary complications in code and it could be easily done on user side
