### ISSUE TITLE
Ubuntu/Large output file size

### ISSUE THREAD

**Issue by edurguti** [JazzCore/python-pdfkit#179]
Hello, I've been using this wonderful tool to convert some html files into PDFs, it worked great on my personal mac but when I dockerized the app to run in ubuntu, the output file is significantly larger, on macOS with python3.8 3MB, on docker image (ubuntu, python 3.8) it's 73MB.
Any ideas?

**Comment by edurguti** [comment]
This issue is resolved for me, kind of - I uninstalled the default package that comes with ubuntu 0.12.5-1 and installed manually via deb package: 0.12.6-1, this worked (text is selectable now and filesize is 3MB).

I am having issues though with fonts, it doesn't seem to like the font that is in my html/css, I'll have to figure that out again.

so:
```
 apt-get remove  wkhtmltopdf
#Download the latest release from https://wkhtmltopdf.org/downloads.html
dpkg -i wkhtmltox_0.12.6-1.buster_amd64.deb # in my case
#got an error and had to install an additional package
apt-get install xfonts-75dpi
```

**Comment by edurguti** [comment]
I ended up using base64 for fonts on in my CSS, more info: https://css-tricks.com/data-uris/

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
