### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by svscorp** [JazzCore/python-pdfkit#18]
Hi there!

I can see this repo is alive. Do you plan to add proxy support?

**Comment by svscorp** [comment]
@JazzCore Sorry for late response. I am using both Ubuntu 14.04 x64 and Debian 7 x64

**Comment by ebuildy** [comment]
+1 , ``wkhtmltopdf`` has an option ``--proxy``.

**Comment by JazzCore** [comment]
This should work out of the box, is anyone still have this issue feel free to reopen
