### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by johnvandeweghe** [JazzCore/python-pdfkit#186]
The last commit was a couple years ago, there are 88 issues, and 20 open PRs (several that fix newer versions of python for example). This interface is great, but it needs some love from the maintainer(s). If it's not going to be worked on a deprecation notice would be good.

**Comment by JazzCore** [comment]
Hello!

Yeah... I've lost interest and need in this project a long time ago, but fortunately for a while @alanhamlett mainated this project for me, but I never gave a PyPI access to anyone, so even there was some work no new releases was made on PyPI, my fault :(

Still, everytime I see a mail about issues and PRs I feel bad for not maintaining it. But now it reached a threshold so I've decided to review all PRs and issues and make a new release in a few coming weeks.

I will be very glad and thankful if somebody stepped in and taken maintenace of this project, for now I'll try to maintain it again.

**Comment by D3X** [comment]
@JazzCore Is there any chance we could get a new release anytime soon?

I'd be happy to take over maintenance of this project if that'd help.

**Comment by JazzCore** [comment]
Just updated PyPI version to most recent master version, sorry again for the long wait, closing for now. @D3X, help would be most welcome, please ping me again if you are still interested, thanks!
