### ISSUE TITLE
Unable to send kerberos credentials if a website using single sign on using kerberos.

### ISSUE THREAD

**Issue by sorabhjainnitj** [JazzCore/python-pdfkit#188]
i am Unable to send kerberos credentials if a website using single sign on using kerberos. let me know the necessary headers required. it's not mentioned in docs as well

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
