### ISSUE TITLE
I want to convert html to pdf we got error in wkhtmltopdf 

### ISSUE THREAD

**Issue by Edvaytech** [JazzCore/python-pdfkit#189]
we want to try converting html to pdf 

pdfkit.from_string(render_template('payment_receipt.html', context= context_pdf), 'payment_receipt.pdf')

it's working fine in ubuntu but when we deploy in our AWS server it's not working

pdfkit==0.6.1
wkhtmltopdf == 0.12.5

this is the OS version

NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.1
PRETTY_NAME="Alpine Linux v3.12"

it's give this error

`backend_1        |   File "/usr/local/lib/python3.7/site-packages/pdfkit/api.py", line 72, in from_string
backend_1        |     return r.to_pdf(output_path)
backend_1        |   File "/usr/local/lib/python3.7/site-packages/pdfkit/pdfkit.py", line 159, in to_pdf
backend_1        |     raise IOError("wkhtmltopdf exited with non-zero code {0}. error:\n{1}".format(exit_code, stderr))
backend_1        | OSError: wkhtmltopdf exited with non-zero code -11. error:
backend_1        | QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
backend_1        | Loading page (1/2)
[=============>                                              ] 23%              ] 0%`

**Comment by floi** [comment]
Looks like an issue with wkhtmltopdf (and not pdfkit) to me. Their FAQ explicitly mentions [alpine's use of musl libc](https://wkhtmltopdf.org/downloads.html#why-do-you-have-static-builds-with-patched-qt), so that might be a lead?

**Comment by JazzCore** [comment]
This is clearly a ``wkhtmltopdf`` binary issue, since pdfkit only wraps it, closing. Check installation guides for your OS and try reinstalling it, usually its a simple ``apt-get`` or similar.
