### ISSUE TITLE
Building option dictionary

### ISSUE THREAD

**Issue by cperezortiz** [JazzCore/python-pdfkit#19]
Hello, sorry if this is not the right place, i needed an answer.

how is it posible to build a dictionary options with cookies or whatever option that requires more than one value?

options = {
        'page-size': 'Letter',
        'margin-top': '0.75in',
        'margin-right': '0.75in',
        'margin-bottom': '0.75in',
        'margin-left': '0.75in',
        'encoding': "UTF-8",
        'no-outline': None,
        'cookie': 'usuario=1, another_cookie=another_value',

**Comment by lexhung** [comment]
I submitted a patch to resolve this in #40

**Comment by JazzCore** [comment]
Implemented in #40
