### ISSUE TITLE
Use pdfkit on Colab

### ISSUE THREAD

**Issue by raul-parada** [JazzCore/python-pdfkit#192]
I'm using pdfkit to convert a Folium html map. When I convert it into pdf using:

import imgkit

from pyvirtualdisplay import Display
import pdfkit
display = Display()

try:
   display.start()  
   pdfkit.from_file('osm1.html', 'out.pdf')
finally:
   display.stop()
I get just a corner of the map

![image](https://user-images.githubusercontent.com/8438920/119495182-6db5ae80-bd62-11eb-97c5-976bb1ca4632.png)

I've tried to add these options but doesn't get more original map.

 options = {
    'page-height': '70in',
    'page-width': '70in',
    }

I get this log output:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Loading page (1/2)
Printing pages (2/2)                                               
Done     

Is it possible to convert the whole map? or at least focus on a given part of it?

In case you want to check it, here are the files: https://drive.google.com/drive/folders/1nzmKSA7kMeBM9Duqb5WW-6_r8V4EgAlG?usp=sharing

**Comment by JazzCore** [comment]
This is clearly a ``wkhtmltopdf`` issue, since pdfkit only wraps it, closing. It's better to check docs for it and ask for support on https://github.com/wkhtmltopdf/wkhtmltopdf
