### ISSUE TITLE
consecutive pages

### ISSUE THREAD

**Issue by yishairasowsky** [JazzCore/python-pdfkit#195]
@amandasaurus @EdwardBetts @lexhung @yohanboniface @alanhamlett 
i love your work. please can you advise me? i want to print pdf pages with running commentaries per line. so for example, instead of the page appearing like this:
    
    line 1
    comment on line 1
    line 2
    comment on line 2
    --page break--
    line 3
    comment on line 3
    line 4
    comment on line 4

i instead want it to appear like this:

    
    line 1
    line 2
    comment on line 1
    comment on line 2
    --page break--
    line 3
    line 4
    comment on line 3
    comment on line 4

i am working in python, and i can show you a sample of my code [here](https://github.com/yishairasowsky/SeferMaker/blob/main/create_pdf.py) 
thank you!!!!

**Comment by JazzCore** [comment]
This is more wkhtmltopdf question, since pdfkit only wraps it, closing. Try asking for support on https://github.com/wkhtmltopdf/wkhtmltopdf
