### ISSUE TITLE
pages

### ISSUE THREAD

**Issue by yishairasowsky** [JazzCore/python-pdfkit#196]
Hi! I love your work. I am trying to make page numbers alternately appear at the bottom left for odd pages and bottom right for even pages. Is there a way to do that?
What I have so far is this...

```
wkhtmltopdf_path = 'C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe'
config = pdfkit.configuration(wkhtmltopdf=wkhtmltopdf_path)
options = {
    'footer-center': '~ [page] of [topage] ~',
```

**Comment by JazzCore** [comment]
This is more wkhtmltopdf question, since pdfkit only wraps it, closing. Try asking for support on https://github.com/wkhtmltopdf/wkhtmltopdf
