### ISSUE TITLE
Generates only Login Page using Jira

### ISSUE THREAD

**Issue by indrojyoti** [JazzCore/python-pdfkit#199]
I am trying to print a Jira Ticket Page using pdfkit. But in return it generates a PDF with the login page.

I am providing the header and cookie in the options section. But still, the actual page is not getting generated.

Any particular option or configuration am I missing?

**Comment by JazzCore** [comment]
This is more wkhtmltopdf question, since pdfkit only wraps it, closing. Try asking for support on https://github.com/wkhtmltopdf/wkhtmltopdf
