### ISSUE TITLE
Save pdf in io.StringIO

### ISSUE THREAD

**Issue by PhilippBuehler** [JazzCore/python-pdfkit#204]
```
import pdfkit
import io
stream = io.StringIO()
pdfkit.from_string("Hello World", stream)
```

>> TypeError: expected str, bytes or os.PathLike object, not StringIO

Is there any chance to write the pdf to the StringIO Buffer?

**Comment by JordanRClark** [comment]
Hey!

I've been creating something using this library, I've found if you pass in bytes it will write to in memory.

For example:
```
html = '<html><body></body></html>'
file = pdfkit.from_string(html, b'')
```

`file` will the become a bytes string in memory and you can use that.

Writing it back to the file system:
```
with open('output.pdf', 'wb') as output:
    output.write(file)
```
Or return it within a Response if you're using django / flask

**Comment by JazzCore** [comment]
You can just call ``pdfkit.from_string("Hello World")``, without any arguments it returns byte string that you can later pass to StringIO
