### ISSUE TITLE
Error: from_url() missing 1 required positional argument: 'output_path'

### ISSUE THREAD

**Issue by viktor02** [JazzCore/python-pdfkit#205]
The readme says that you can save the pdf as an object, but I get an error that the path argument is missing 
```
# Without output_path, PDF is returned for assigning to a variable
pdf = pdfkit.from_url('http://google.com')
```
```
Error: from_url() missing 1 required positional argument: 'output_path'
```

**Comment by JazzCore** [comment]
Hello! 

Yes, current README is for master branch state, while PyPI version heavily lags behind for now...

For current PyPI version correct syntax is ``pdf = pdfkit.from_url('http://google.com', False)``. I'll update PyPI it the near future.
