### ISSUE TITLE
GLIBC Error 

### ISSUE THREAD

**Issue by capriciousduck** [JazzCore/python-pdfkit#206]
I get the following error when converting an HTML page to pdf

`/usr/local/bin/wkhtmltopdf: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/wkhtmltopdf)`

What do I do now?

**Comment by JazzCore** [comment]
This is clearly a ``wkhtmltopdf`` binary issue, since pdfkit only wraps it, closing. Check installation guides for your OS and try reinstalling it, usually its a simple ``apt-get`` or similar.
