### ISSUE TITLE
PyPi repository out of date!!!

### ISSUE THREAD

**Issue by clarcked** [JazzCore/python-pdfkit#208]
Can we update this project on PyPi ? 
The last version was released on Jan 9, 2017.
And there is a beautiful warning:
`/pdfkit/source.py:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.type is 'file':`

**Comment by JazzCore** [comment]
Hello!

Just made a new release and updated PyPI, sorry for the long wait. Warning should be also fixed in recent changes, thanks!
