### ISSUE TITLE
winerror 6 invalid handle

### ISSUE THREAD

**Issue by centerionware** [JazzCore/python-pdfkit#21]
When I tried running pdfkit under boost::python in an fcgi application run by apache on windows 7, it was throwing the error in the title. I would guess it might fail the same way under pythonw, but didn't test that.

I managed to fix it by adding pipe handlers to stdin and stderr in configuration.py. I changed it to:
[code]
            if sys.platform == 'win32':
                proc = subprocess.Popen(['where', 'wkhtmltopdf'],stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
                self.wkhtmltopdf = proc.stdout.read().strip()
[/code]
I don't know if separating it into two statements is necessary, but since it started working with that I haven't tried changing it back to .communicate()[0].strip()

The error appears to be related to not launching it from a console and the stdin, stderr, and stdout not having handles to default to.

**Comment by cbergmiller** [comment]
This still seems to be an issue. I ran into it using pdfkit in a django view run by IIS with [wfastcgi](https://pypi.python.org/pypi/wfastcgi) on a Windows Server 2012R2.
Would a PR be accepted that resolves this problem?

**Comment by eagleEggs** [comment]
Seeing this on Windows 7, not on Windows 10.

![image](https://user-images.githubusercontent.com/29800532/52871470-21597e00-3118-11e9-89cf-e58a2b392ef9.png)

**Comment by mattburlage** [comment]
Has there been any movement on this? There is a similar issue and fix for django-wkhtmltopdf (see https://stackoverflow.com/questions/55259645/django-wkhtmltopdf-on-iis-winerror-6-the-handle-is-invalid) but I can't seem to figure out how to apply it to pdfkit. Thanks.

**Comment by JazzCore** [comment]
Sure, I'll accept any PR that fixes an issue and does not break existing code base, if you are still up to it.

Sorry that it took so long for me to answer!
