### ISSUE TITLE
I would like to use disable-smart-shrinking option

### ISSUE THREAD

**Issue by ugoQ** [JazzCore/python-pdfkit#211]
I am enable to use `disable-smart-shrinking` option because I'm on Ubuntu and I am forced to use wkhtmltopdf whitout the QT patches, downgrading to a patched wkhtmltopdf version (0.12.4) gives an error starting like this:
```
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
```

There is this warning in main page:
> Warning! Version in debian/ubuntu repos have reduced functionality (because it compiled without the wkhtmltopdf QT patches), such as adding outlines, headers, footers, TOC etc. To use this options you should install static binary from wkhtmltopdf site or you can use this script.

("this script" link is broken)
Anybody has a solution to help me?
Thanks in advance.

**Comment by sscotti** [comment]
You might want to look at this:

https://stackoverflow.com/questions/42094214

Might be related to your libssl package version ?

**Comment by ugoQ** [comment]
Thanks for your reply, it seems to be my problem (haven't tried the solution).
I had some time to think about this, and downgrading is not a solution for us. I'll just adapt my contents to be better displayed in the final pdf.

You can close this issue if you want.

**Comment by sscotti** [comment]
I'm not the maintainer.  Not sure that you would have to downgrade though.  I have the wkhtmltox-0.12.4 package running in a Docker Container that runs Debian Bulleye.  I think it uses apt-get --assume-yes install libssl1.1.

**Comment by JazzCore** [comment]
@ugoQ You can try to either download a binary from [official site](https://wkhtmltopdf.org/downloads.html) (they got deb packages for Ubuntu) or try using [this script](https://github.com/JazzCore/python-pdfkit/blob/master/ci/before-script.sh) which I use on CI servers for tests (its the one with broken link, I'll fix it though). Closing this for now, feel free to reopen if needed
