### ISSUE TITLE
Broken Link on Github - "you can use this script.", ? use in Docker running Bullseye

### ISSUE THREAD

**Issue by sscotti** [JazzCore/python-pdfkit#213]
The link on this page:  [ReadMe](https://github.com/JazzCore/python-pdfkit/blob/master/README.rst) that says "you can use this script." is broken.

I also recently upgraded some of my Docker containers to use Debian Bullseye instead of Buster, and it looks like maybe that partially broken some of the features.  The relevant parts of my DockerFile are as following, using Debian Bullseye

RUN pip3 install pdfkit
RUN pip3 install imgkit

RUN apt-get --assume-yes install xvfb
RUN apt-get --assume-yes install xorg
RUN apt-get --assume-yes install xz-utils

COPY wkhtmltox-0.12.4_linux-generic-amd64.tar.xz /
RUN tar xvJf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
RUN cp wkhtmltox/bin/wkhtmlto* /usr/bin/

I'm not sure that is "correct" now, and if it was / is even necessary to install xvfb, xorg.  wkhtmltox-0.12.4_linux-generic-amd64.tar.xz might be a bit outdated at this point.

I would prefer to maybe just use a static build for Debian BullsEye that will work in my container with QT support because I do not anticipate upgrading that anytime soon really.  It looks like there are not any static builds for BullsEye yet though ?

See:  [Downloades](https://wkhtmltopdf.org/downloads.html)

**Comment by ugoQ** [comment]
In the last issue I commented about the link being broken too.
I was given [that link](https://github.com/JazzCore/python-pdfkit/blob/master/ci/before-script.sh), if it helps.

Also, I managed to install the 0.12.6-1 (with patched QT) using this on Ubuntu, but this totally broke my pdfs content.
```
wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
sudo apt install ./wkhtmltox_0.12.6-1.focal_amd64.deb
```

**Comment by JazzCore** [comment]
Link is fixed now, @ugoQ provided [correct one](https://github.com/JazzCore/python-pdfkit/blob/master/ci/before-script.sh) that I use on GH CI servers with Ubuntu 18.04 bionic. It could work on more fresh Debian/Ubuntu versions, but not guaranteed. Since installation is so different on various distribs I cannot give any tips, you should find correct list of packages that works for your case

**Comment by sscotti** [comment]
Thanks.  

In my DockerFile I changed what I had to this:

# Needed for the .deb pacakge, section below builds the wkhtmltopdf package

RUN apt-get --assume-yes install fontconfig
RUN apt-get --assume-yes install xfonts-75dpi
RUN apt-get --assume-yes install xfonts-100dpi
RUN apt-get --assume-yes install xfonts-scalable
RUN apt-get --assume-yes install xfonts-base

COPY wkhtmltox_0.12.6-1.buster_amd64.deb /
RUN dpkg -i wkhtmltox_0.12.6-1.buster_amd64.deb

and that actaully seemed to work, even though I am using Debian11 as a base image.  I'll do further testing, but the Docker Container builds and wkhtmltopdf, wkhtmltoimage and pdfkit still seem to work.
