### ISSUE TITLE
Doubt - Add Water Mark to PDF

### ISSUE THREAD

**Issue by carlosdorneles-mb** [JazzCore/python-pdfkit#217]
Hello, I would like to know if the library has any feature to add Water Mark to the pages of the managed PDFs.

Example:
![createwatermarks_5](https://user-images.githubusercontent.com/87037175/150541461-eecbff1d-7123-40ec-b03e-97c6480d44d0.png)

**Comment by sscotti** [comment]
Not sure that it is supported out-of-the-box, but there are ways to do something similar:

[wkhtmltopdf-repeatitive-background-image-on-all-pages](https://stackoverflow.com/questions/24755428/wkhtmltopdf-repeatitive-background-image-on-all-pages)

[adding-a-watermark-with-wkhtmltopdf](https://www.api2pdf.com/adding-a-watermark-with-wkhtmltopdf/)

**Comment by carlosdorneles-mb** [comment]
Thanks @sscotti
