### ISSUE TITLE
set url for from_string parsing

### ISSUE THREAD

**Issue by 0xdeadc0de** [JazzCore/python-pdfkit#22]
Is it possible to set a url for from_string parsing? I'm using pdfkit to parse the output from my (custom) CMS system, obviously using from_string, but when trying to include images using relative links (eg: img src="/images/logo.png") it tries to load from file:///images/logo.png, and I'd like to somehow tell it all relative links are relative to http://server.com/path/to/request - instead of the altnerative of hacky regex replacements on all links before passing the string. It seems to do the same when the page has links to javascript files. It didn't warn about CSS inclusions, but I'd bet they're not recognized properly either.

**Comment by JazzCore** [comment]
Don't know, sorry. Anyway, it should be implemented on ``wkhtmltopdf`` side since it does all main work, so you can ask upstream for this feature.

**Comment by svscorp** [comment]
@0xdeadc0de it is not possible. When wkhtml is doing a 'screenshot' it renders a page. It is obvious it is trying to load it with relative path. 

The best thing you can do here is to:

````
replaced_html = re.sub(r'(src|href)="\/', r'\g<1>="http://www.mywebsite.com/', replaced_html)
````
