### ISSUE TITLE
"You will need to run whktmltopdf within a "virutal" X server" error when being executed within crontab job

### ISSUE THREAD

**Issue by svscorp** [JazzCore/python-pdfkit#24]
I am getting an exception when my script is being executed by crontab job:

```
You will need to run whktmltopdf within a "virutal" X server.
Go to the link above for more information
https://github.com/JazzCore/python-pdfkit/wiki/Using-wkhtmltopdf-without-X-serverUse exit() or Ctrl-D (i.e. EOF) to exit
```

If I run the script manually - it works and saves html to pdf. So of course I did that magic which is written in the URL above. But it doesn't help when script is executed within crontab (root user)

Debian 7

**Comment by svscorp** [comment]
Some investigation:

1. I checked the arguments PDFKit is calling wkhtmltopdf with that way (from string, btw, that's why 3rd argument is '-'):
````
['/usr/bin/wkhtmltopdf', '--quiet', '-', '497479169.pdf']
````
2. With https://github.com/JazzCore/python-pdfkit/wiki/Using-wkhtmltopdf-without-X-server
We are making the shortcut in /usr/bin/wkhtmltopdf.sh and then the symlink here: ln -s /usr/bin/wkhtmltopdf.sh /usr/local/bin/wkhtmltopdf

3. When cron is executing the python script, even a simple one

````
#!/usr/bin/python3

import pdfkit

options = {
    'quiet': ''
}

print('start')
pdfkit.from_url('http://google.com', '/tmp/google.pdf', options=options)
print('stop')
````

PDFKit is calling /usr/bin/wkhtmltopdf when is being executed from CRON. When it is executed from command line it uses our shortcut /usr/local/bin/wkhtmltopdf

**Comment by JazzCore** [comment]
You can try to specify path to binary by hand, see here: https://github.com/JazzCore/python-pdfkit#configuration

**Comment by svscorp** [comment]
Hi @JazzCore 

Thanks for your answer.

I tried that:

````
print(config['DEFAULT']['wkhtmltopdfPath']) # outputs correct: /usr/bin/wkhtmltopdf
pdfConfiguration = pdfkit.configuration(wkhtmltopdf=config['DEFAULT']['wkhtmltopdfPath'])
    pdfkit.from_string(html_string, 'default.pdf', configuration=pdfConfiguration)
````

is giving me this error:

````
  ...
  File "/usr/local/lib/python3.4/dist-packages/pdfkit/api.py", line 66, in from_string
    configuration=configuration)
  File "/usr/local/lib/python3.4/dist-packages/pdfkit/pdfkit.py", line 40, in __init__
    self.wkhtmltopdf = self.configuration.wkhtmltopdf.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
````

**Comment by jorge-marques** [comment]
I'm having the same problem as @svscorp. Using python 3.4.3.

**Comment by ZChen-EDR** [comment]
@svscorp your answer saved my life. thanks so much

**Comment by JazzCore** [comment]
Should be fixed now, closing
