### ISSUE TITLE
support for header/footer

### ISSUE THREAD

**Issue by vyscond** [JazzCore/python-pdfkit#27]
is there possible to set a header/footer with an html code too? if not can we have it? :)

**Comment by tttomekkk** [comment]
I'm not associated with this project, but I can tell it is:)
Use options like this : `{'header-html': '<h1>my header</h1>', 'footer-html': '<h6> my footer </h6>' }`.
All possible options are available in [wkhtmltopdf manual](https://madalgo.au.dk/~jakobt/wkhtmltoxdoc/wkhtmltopdf-0.9.9-doc.html), from my own experience I would say all or most of them can be used with pdfkit.

**Comment by joeydi** [comment]
@tttomekkk That comment is incorrect. 'header-html' and 'footer-html' require a URL to an HTML document.

    wkhtmltopdf reported an error:
    Error: --header-html should be a URL and not a string containing HTML code.

**Comment by tttomekkk** [comment]
@joeydi Yeah, you are right, this should be URL. Anyway, footer/header with HTML content is achievable that way.
