### ISSUE TITLE
The CSS background-image url only works when its absolute

### ISSUE THREAD

**Issue by Leprosy** [JazzCore/python-pdfkit#28]
The CSS background-image url only works when it's an absolute path on my machine, when it's relative, the image don't appear on the rendererd PDF. I found this seems to be a limitation of the wkhtml2pdf, is that true?

**Comment by jebsky** [comment]
It seems to be this way for images in general

**Comment by JazzCore** [comment]
Closing due to date, feel free to reopen if you need ping me about this issue. 

Sorry that it took so long for me to get to it...
