### ISSUE TITLE
WKHtmltoPdf "specified in incorrect location" error

### ISSUE THREAD

**Issue by NaraJeamfry** [JazzCore/python-pdfkit#29]
Good morning, 

I've been working with python-pdfkit to generate pdfs on a Django app and everything was running perfectly on our Windows builds, but we had to upload the project to a Linux VPS (using Ubuntu 12.04). I have been working on installing a correct wkhtmltopdf build that works correctly with everything, and I have been able to use it from the command line, but running it from Python fails.

I have been able to extract the definitive command issued from the Python code and the arguments seem to be ordered "randomly" (actually, on the hashed order from Python), which halts wkhtmltopdf because it cannot work with unordered arguments.

**Comment by JazzCore** [comment]
Honestly, don't know whats happening here, you can try to run tests with ``python setup.py test``. I'll try to look into it, but it can take some time since I don't have much free time atm.

**Comment by Nara-Jeamfry** [comment]
Alright, I'll be testing this now, I will post any new info I have! :D

**Comment by Nara-Jeamfry** [comment]
Reporting some things:

The error reported by Python is an Exec format error. The error reported by wkhtmltopdf if I copy the exact cmd command on the server is "--margin-left specified in incorrect location". Additional data on the wkhtmltox installation is: 

Name:
  wkhtmltopdf 0.12.2.1 (with patched qt)

The header commands are working correctly if the parameters are ordered as asked by the wkhtmltopdf executable. I'll check how to fix that in the current server.

From the setup.py tests, 5 fail. I'll also check which tests are failing and whether it is related to the unordered parameters issue.

**Comment by Nara-Jeamfry** [comment]
Further information:

Tests failing: 
* TestPDFKitGeneration.test_pdf_generation
  * Fails on: Popen, [Errno 8] Exec format error, subprocess.py:1249
* TestPDFKitGeneration.test_pdf_generation_from_file_like
  * Fails on: Popen, [Errno 8] Exec format error, subprocess.py:1249
* TestPDFKitGeneration.test_raise_error_if_bad_wkhtmltopdf_option
  * Fails on: Popen, [Errno 8] Exec format error, subprocess.py:1249
* TestPDFKitGeneration.test_raise_error_with_invalid_url
  * Fails on: Popen, [Errno 8] Exec format error, subprocess.py:1249
* TestPDFKitGeneration.test_wkhtmltopdf_error_handling
  * Fails on: Popen, [Errno 8] Exec format error, subprocess.py:1249

There seem to exist some problems when passing concrete arguments to the wkhtmltopdf process. I'll be trying to check this issue further.

**Comment by emilymye** [comment]
Sorry to butt in, but I was getting these errors too and fixed it by adding a "#!/bin/sh" shebang to the shell file for X-server setup you symlink as the wkhtmltopdf executable . I don't know if that will help but in general it seems to be a problem with how that script is getting executed.

**Comment by JazzCore** [comment]
Closing due to date, feel free to reopen if you need ping me about this issue.

Sorry that it took so long for me to get to it...
