### ISSUE TITLE
Different behaviour on localhost and server

### ISSUE THREAD

**Issue by cjdp25** [JazzCore/python-pdfkit#30]
Hello, I'm having an issue with pdfkit.

I'm using this to create a PDF, attaching to email and sending it with MandrillApp
this is the code I use to generate the PDF:
   pdf = pdfkit.from_url(link, False)

That works on localhost but when I upload it to my server, it doesn't work and has a Exception ("from_url() missing 1 required positional argument: 'output_path'",) so I added a None as first attribute and again another Exception ("invalid literal for int() with base 10: 'None'",) so I put an integer as the first argument
    pdf = pdfkit.from_url(0, link, False)

It works, generate the PDF and sends to mail, but when I want to open the PDF, the reader says it's not a valid PDF file, I only managed to open the generated PDF it with Okular (KDE's default reader).

What can I do to have this working as in localhost on the server?
(attached a screenshot of the code)

![snapshot108](https://cloud.githubusercontent.com/assets/141861/8152676/1ab56bc6-12e6-11e5-8cbe-f25148eee2b5.jpg)

**Comment by JazzCore** [comment]
Actually this is super weird since there is no ``from_url`` method with signature that takes int as a first parameter. Honestly, don't know whats happening here, you can try to run tests with ``python setup.py test``. I'll try to look into it, but it can take some time since I don't have much free time atm.

**Comment by JazzCore** [comment]
Also looks related to #29, maybe a duplicate

**Comment by Nara-Jeamfry** [comment]
After checking on more details for my issue I think this is not related, as it generates PDFs (even though they are corrupt, or something). My issue is related more to an issue with wkhtmltopdf. Thanks anyway!
