### ISSUE TITLE
why  convert <td>ce2d842c</td> to c \n e \n 2 \n d \n 8 \n 4 \n 2\n c\n?

### ISSUE THREAD

**Issue by minipaintf** [JazzCore/python-pdfkit#34]
I have code like "<td>ce2d842c</td>"in my html-file.It looks like "ce2d842c" in my browser.But it looks like this"c
            e
            2
            d
            8
            4
            2
            c" in my pdf-file which was converted from the html-file by pdfkit.from_file().

**Comment by Swiftkilla** [comment]
@minipaintf Pleae can you provide further information?

If possible, the specific section within the HTML file you are trying to convert.

Best regards,
Swift

**Comment by Swiftkilla** [comment]
Also, if there is any CSS associated with the elements (child and parent elements might be required).

**Comment by Swiftkilla** [comment]
If you can post-process the string, a simple solution in Python would be:

```
string = 'c\ne\n2\nd\n8\n4\n2\nc'
string.replace('\n','')

```

**Comment by JazzCore** [comment]
Closing due to date, feel free to reopen if you need ping me about this issue.

Sorry that it took so long for me to get to it...
