### ISSUE TITLE
https://github.com/JazzCore/python-pdfkit/wiki/Using-wkhtmltopdf-without-X-server

### ISSUE THREAD

**Issue by GenericUK** [JazzCore/python-pdfkit#35]
https://github.com/JazzCore/python-pdfkit/wiki/Using-wkhtmltopdf-without-X-server

In your setup, shouldn't the bash link match the symlink?

/usr/local/bin/wkhtmltopdf INSTEAD OF /usr/bin/wkhtmltopdf

**Comment by micrypt** [comment]
@GenericUK Are you running into any errors with the bash script? It seems to work just fine. I've just made a minor edit to that wiki though.

**Comment by GenericUK** [comment]
Sorry, I'm not sure what I got the warning in, I think it was ERPNext. But changing the link in the bash fixed it. Before I was still getting x server not found.

**Comment by alanhamlett** [comment]
Should be resolved when #44 is fixed.

**Comment by JazzCore** [comment]
Closing due to date, feel free to reopen if you need ping me about this issue.

Sorry that it took so long for me to get to it...
