### ISSUE TITLE
stdout, stderr = result.communicate(input=input) hangs and takes a long time to load

### ISSUE THREAD

**Issue by javierwonghf** [JazzCore/python-pdfkit#36]
I have an issue with using PDFKIT whereby for some strange reason generating a simple PDF takes > 17s which honestly shouldn't be the case.

Further diagnosis reveals that the WKHTMLTOPDF process runs at 99% - 100% CPU utilization for the period of time that the PDF is being generated.

Using CPROFILE for Python, I can narrow down to the following that seems to be the root cause (this runs for 17s+):

69 17.196 0.249 17.196 0.249 {built-in method poll}

Some environment details are as follows:

Host OS: VMWare ESXi 5.1
Guest OS: Ubuntu 14.04.3 LTS 64 bit
Guest CPU: 4 x Cores Intel Xeon E5506
Guest RAM: 4GB
WKHTMLTOPDF Version: 0.12.2.1 (with patched qt) 64 bit

I have further narrowed it down to stdout, stderr = result.communicate(input=input) which is present in pdfkit.py which seems to be the line that is causing the slowness.

Does anyone have any idea what this "built-in method poll" item is and why result.communicate may be contributing to slow PDF generation and high CPU usage?

Thanks.

**Comment by mmarchini** [comment]
I'm not sure, but I think [Popen.communicate()](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.communicate) uses the built-in method [select.poll()](https://docs.python.org/2/library/select.html#select.poll) to retrieve both the buffers. 

Try executing wkhtmltopdf from the command-line, passing the same HTML you're passing on your Python code, to see how much time it takes to generate the PDF.

**Comment by bohlian** [comment]
< 2 seconds 

i've been trying to search up why would select.poll() take so much time but really haven't come across anything. 

Any ideas where else i can look?

**Comment by mmarchini** [comment]
Take a look at this StackOverflow answer, maybe it's related to your problem:
http://stackoverflow.com/a/2408670/2956796

Can you paste a snippet of your code?

**Comment by bohlian** [comment]
Here is a code snippet. It hangs on from_string. Thanks for the link will look through it now and let you know if I find anything.

```python
try:
		pdfkit.from_string(html, fname, options=options or {})
	except IOError, e:
		if "ContentNotFoundError" in e.message:
			frappe.throw(_("PDF generation failed because of broken image links"))
		else:
			raise
```

**Comment by mmarchini** [comment]
Okay, maybe I've found it. Do you have a complex HTML? With `border-radis`, `gradients`, `backgrounds` and etc.? `wkhtmltopdf` seems to have performance problems with some CSS properties. 

I was able to reproduce the slowness problem with the following code:
```python
import pdfkit
html = """
<html>
    <body>
        <div style="margin: 0px auto; width:1005px; border:1px solid  black; border-radius:6px; background-color:blue">
            <div style=" background-color:green; border:1px solid  red;border-radius:6px;margin-top:13px; position:relative;">
                1<br>2<br>3<br>4<br>5<br>6<br>7<br>8<br>9<br>10<br>
                11<br>12<br>13<br>14<br>15<br>16<br>17<br>18<br>19<br>20<br>
                21<br>22<br>23<br>24<br>25<br>26<br>27<br>28<br>29<br>30<br>
            </div>
        </div>
    </body>
</html>
"""

fname = "out.pdf"

options={}

try:
    pdfkit.from_string(html, fname, options=options or {})
except IOError, e:
    raise
```

It took 5 seconds to generate the PDF. Without any CSS property, it takes less than 1 second.

Take a look at this issue:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1510

**Comment by bohlian** [comment]
@mmarchini thanks for your response. Sorry for the late reply.

I have done more extensive testing, I have now 2 environments supposedly with the same OS, same patch level, both generating the same PDFs. One does it in 2 seconds, the other in 15 seconds for the exact same PDF. I am absolutely confused.

Both dont have complex HTML.

I have a strange feeling it is something related to the operating system or the network configuration.

Do you have any other ideas on where i may look?

**Comment by bohlian** [comment]
Ah FINALLY!

I cannot believe I missed this all this while, for Ubuntu there is reduced functionality and some dependencies need to be installed. I think perhaps one or two were missing or misbehaving. I reinstalled them and its back to normal!

Just ran the following:

`sudo apt-get install -y openssl build-essential xorg libssl-dev`

Thanks!

**Comment by JazzCore** [comment]
Looks fixed, feel free to reopen if you need ping me about this issue.

Sorry that it took so long for me to get to it...
