### ISSUE TITLE
How to convert page that is loading data? 

### ISSUE THREAD

**Issue by denisvolokh** [JazzCore/python-pdfkit#37]
Hi,

I have page that is populating grid from external resource via rest api. After converting page with pdfkit the table is empty. 

Can pdfkit wait until all data is loaded?

**Comment by mmarchini** [comment]
You probably want these options:

```
--window-status <windowStatus>  Wait until window.status is equal to this
                                string before rendering page
--javascript-delay <msec>       Wait some milliseconds for javascript
                                finish (default 200)
--no-stop-slow-scripts          Do not Stop slow running javascripts
```

`--window-status` is probably the best option here, because you can control exactly when your page will be rendered by `wkhtmltopdf`

Maybe these links will help too:
http://wkhtmltopdf.org/usage/wkhtmltopdf.txt
https://groups.google.com/forum/#!msg/wkhtmltopdf-general/vWDe5hUAyJ8/2XbXM2g1ZtYJ: 
http://stackoverflow.com/questions/15837932/wkhtmltopdf-with-javascript-delay-not-working

**Comment by denisvolokh** [comment]
Thank you your hint. I am going to try window status.

**Comment by denisvolokh** [comment]
Looks like there is problem with rendering when link is in this format *www.site.com/#/invoice* but it works when I put page like *www.site.com/invoice.html*.

I could not find any options for this case.

**Comment by mmarchini** [comment]
Are you using any framework (Angular, Backbone, Ember, etc.)? Have you tried rendering this page manually with `wkhtmltopdf` from the command line?

**Comment by AhmedJaballah** [comment]
Hi,
I have the same issue i have tryed with the options :
--javascript-delay <msec>     
--no-stop-slow-scripts       

But no way plz help

**Comment by anuj-bluebash** [comment]
Getting blank pages for React App pages

**Comment by JazzCore** [comment]
Looks like wkhtmltopdf issue, since it does page parsing and processing, closing.

Sorry that it took so long for me to get to it...

**Comment by zogmwa** [comment]
I have same issue.
Is there any updates for this issue?
