### ISSUE TITLE
libpng error: IDAT: CRC error

### ISSUE THREAD

**Issue by jaredvacanti** [JazzCore/python-pdfkit#39]
I'm getting an error generating pdf from html using pdfkit with `<img>` tags using interlaced pngs (that are transparent). My only error I get ouput is 
```
libpng error: IDAT: CRC error
```
but nothing more verbose than this. The pdf generates but there are no images if it's interlaced, and the non-interlaced (non-transparent) images load. Any ideas?

**Comment by kengruven** [comment]
Upstream has a bug report: wkhtmltopdf/wkhtmltopdf#2622.  They might be interested to hear if it's related to transparency and/or interlacing.

**Comment by JazzCore** [comment]
Error is on wkhtmltopdf side, sadly I cant help here
