### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode . . . 

### ISSUE THREAD

**Issue by quietlyconfident** [JazzCore/python-pdfkit#42]
When I try to use python-pdfkit with certain HTML content that has certain characters in it, it fails with one of these errors if the html content is loaded into memory:

```
File ". . . /pdfkit.py", line 100, in to_pdf
    input = self.source.to_s().encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 64: ordinal not in range(128)
```

or 

```
File ". . ./pdfkit.py", line 102, in to_pdf
    input = self.source.source.read().encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 64: ordinal not in range(128)
```

But, python pdfkit works just fine if it is provided with just a filename, and so does wkhtmltopdf.

I think that python pdfkit is doing something unsafe with strings; perhaps it should assume that the input is just bytes.

[python-pdfkit error demo.zip](https://github.com/JazzCore/python-pdfkit/files/58837/python-pdfkit.error.demo.zip)

**Comment by debaetsr** [comment]
I have also problems when the source is already in utf-8 (encoding utf-8 to utf-8 gives weird results). 

Removing the encode works for me. My HTML source files are in UTF-8, as we have many accents in Belgium.

I assume it's the programmers job to ensure correct encoding before calling the library, so he can be in complete control what to do if unsupported characters occur.

Regards,
Ruben

**Comment by patrickyan** [comment]
@debaetsr how did you fix the problem?

**Comment by alanhamlett** [comment]
Should be fixed on master branch with #81 and released in the next version.

**Comment by gbrowdy** [comment]
The commit you referenced deals with the decoding, whereas the problem stated here (which I am also having) is about the encode function in the to_pdf method.

**Comment by alexandrezia** [comment]
I'm also having this issue,
All my html files are already utf-8 as they are in Portuguese language.

**Comment by mdesjardins** [comment]
I am having the same problem, with the French language, also utf-8.

**Comment by JazzCore** [comment]
Should be fixed now.

Sorry that it took so long for me to get to it...
