### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by bhaskar8088** [JazzCore/python-pdfkit#43]
Hello,

Please look at the below error trace.

<pre>
In [1]: import pdfkit

In [2]: pdfkit.from_string('a', 'a.pdf')
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-5d4c6076de2d> in <module>()
----> 1 pdfkit.from_string('a', 'a.pdf')

/root/.virtualenvs/v1/lib/python2.7/site-packages/pdfkit/api.pyc in from_string(input, output_path, options, toc, cover, css, configuration)
     66                configuration=configuration)
     67 
---> 68     return r.to_pdf(output_path)
     69 
     70 

/root/.virtualenvs/v1/lib/python2.7/site-packages/pdfkit/pdfkit.pyc in to_pdf(self, path)
     91 
     92         result = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
---> 93                                   stderr=subprocess.PIPE)
     94 
     95         # If the source is a string then we will pipe it into wkhtmltopdf.

/usr/lib/python2.7/subprocess.pyc in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags)
    708                                 p2cread, p2cwrite,
    709                                 c2pread, c2pwrite,
--> 710                                 errread, errwrite)
    711         except Exception:
    712             # Preserve original exception in case os.close raises.

/usr/lib/python2.7/subprocess.pyc in _execute_child(self, args, executable, preexec_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell, to_close, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
   1325                         raise
   1326                 child_exception = pickle.loads(data)
-> 1327                 raise child_exception
   1328 
   1329 

OSError: [Errno 8] Exec format error
</pre>

Not sure if this is an issue or some fault from my side, it was working in my local system(installed long back) but not working in digital ocean server.

I followed instructions from this page - http://fedir.github.io/web/blog/2013/09/25/install-wkhtmltopdf-on-ubuntu/

Please let me know if I missed anything.

**Comment by bhaskar8088** [comment]
Solution from this link is working for me(for Ubuntu 14):

http://askubuntu.com/a/605644

**Comment by alanhamlett** [comment]
Should be resolved when #44 is fixed.

**Comment by corpulent** [comment]
This worked for me.

First do the install from here http://askubuntu.com/a/605644 like @bhaskar8088 suggests, and then do this:

```
echo -e '#!/bin/bash\nxvfb-run -a --server-args="-screen 0, 1024x768x24" /usr/bin/wkhtmltopdf -q $*' > /usr/bin/wkhtmltopdf.sh
chmod a+x /usr/bin/wkhtmltopdf.sh

rm -f /usr/local/bin/wkhtmltopdf
ln -s /usr/bin/wkhtmltopdf.sh /usr/local/bin/wkhtmltopdf
```

**Comment by savad** [comment]
Guys, anyone have any idea? How to fix this issue in mac sierra OS?

**Comment by sunxu3074** [comment]
> Guys, anyone have any idea? How to fix this issue in mac sierra OS?

I hava same issue. Are you solve it?

**Comment by JazzCore** [comment]
Closing due to date, feel free to reopen if you need ping me about this issue.

Sorry that it took so long for me to get to it...
