### ISSUE TITLE
Using xvfbwrapper instead of custom bash script

### ISSUE THREAD

**Issue by vstoykov** [JazzCore/python-pdfkit#44]
I think that will be a lot more painless if there is builtin integration with `xvfbwrapper` (https://github.com/cgoldberg/xvfbwrapper). If there is no `DISPLAY` environment variable then try to start Xvfb with the wrapper.

**Comment by JazzCore** [comment]
If someone willing to make a PR for this I'll surely merge it if it's used only when user specifies for it, for now current workaround with virtual X server is quite fine.

Sorry that it took so long for me to get to it...
