### ISSUE TITLE
Pass custom request headers for URL in pdfkit.

### ISSUE THREAD

**Issue by rohitstatic** [JazzCore/python-pdfkit#45]
I am trying to convert a URL to pdf using pdfkit in python as follows.

import pdfkit
pdfkit.from_url(url, file_path)

I wanted to know is there some way to pass custom request headers with this URL such as X-Proxy-REMOTE-USER to something.

Regards
Rohit

**Comment by kute** [comment]
maybe this can help [#53](https://github.com/JazzCore/python-pdfkit/issues/53)

**Comment by JazzCore** [comment]
Now there are, pass it in options like this:

    'custom-header' : [
        ('Accept-Encoding', 'gzip')
    ]
