### ISSUE TITLE
Request: image (wkhtmltoimage) support

### ISSUE THREAD

**Issue by kengruven** [JazzCore/python-pdfkit#51]
PDFKit is great for converting a webpage to PDF.  Another program in the same (Debian) package as it is wkhtmltoimage, which can turn a webpage into PNG/SVG/etc.

We do this, too, but since pdfkit doesn't support that yet (right?), we basically have to do most of the subprocess guts ourselves.  It works, but it's less fun (and more error-prone) than pdfkit.

It would be great if PDFKit supported PNG/SVG through a similar interface so we could simplify our application, and take advantage of everything PDFKit provides for wkhtmltopdf.

**Comment by mgallagher** [comment]
+1

**Comment by freetest** [comment]
+1 

i use pdfkit.from_string(html,'out.pdf')

html include images  when convert finishe . the  images not in out.pdf

**Comment by ShipraShalini** [comment]
+1

**Comment by liumingmusic** [comment]
+1

**Comment by hackinteach** [comment]
+1

**Comment by Mitaanshu** [comment]
+1

**Comment by DeppWang** [comment]
+1

**Comment by JazzCore** [comment]
I'll surely accept a PR for this if someone willing to make it, for now it's hard to find time even to maintain this project.

Sorry that it took so long for me to get to it...
