### ISSUE TITLE
Wide page cuts off and no overflow.

### ISSUE THREAD

**Issue by haincha** [JazzCore/python-pdfkit#52]
Hey, been using this for a specific project I am working on. The HTML I have renders properly in the browser, but when the pdfkit converts it and cuts off the extra information on the page outside of letter format.

Is there any way to fix this? I double checked. Printing the same page results in the same error in a browser. It looks to be fairly common when printing HTML. The HTML is converted from a wide spreadsheet.

**Comment by dinukadesilva** [comment]
I'm facing the same issue. I have a report having a quite large spreadsheet and I want that to be exactly  reprinted resized in the pdf A4 size. Basically I want to get the content fit to the page size. Is this doable?

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result.

Sorry that it took so long for me to get to it...

**Comment by haincha** [comment]
lol, if I remember correctly, I figured out a solution. But, I've been off this project for almost five years. 😄

**Comment by parthch11** [comment]
> lol, if I remember correctly, I figured out a solution. But, I've been off this project for almost five years. 😄

Hi, if you remember or able to trace back the solution, could you please share it?
It will be really useful.
