### ISSUE TITLE
How to custom Head and Proxy ?

### ISSUE THREAD

**Issue by Zonzely** [JazzCore/python-pdfkit#53]
Hi!
I want to custom the http head and proxy. I try some code, but I fail.

```
#!/usr/bin/env python
# encoding: utf-8


import pdfkit
import requests

url = 'http://www.baidu.com'
headers = {'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/48.0.2564.82 Chrome/48.0.2564.82 Safari/537.36'}
proxy ={'http': '113.119.82.69:9000'}
options = {
        'custom-header':headers,
        'proxy': proxy
        }


pdfkit.from_url(url,'out.pdf',options=options)
```

**Comment by anandpdoshi** [comment]
Use python `requests` to get the html and use `pdfkit.from_string` instead 😄

**Comment by Zonzely** [comment]
I have try the `requests` and use `pdfkit.from_string`,but sometime pictures in html don't download.

**Comment by kute** [comment]
You should add '--' in each header-name and pass it to `options` directly. Like this blow:


    url = "https://github.com/JazzCore/python-pdfkit"
    headers = {
            '--header-line': 'this is a head line',
            '--load-error-handling': 'ignore',
            '--header-left': 'header left text====='
        }
    pdfkit.from_url(url=[url], output_path='./pdfkit2.pdf', options=headers)

finally, it generates the pdf with [wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf)，so you should learn that what headers it supports and i have not learned deeply, some are:

      --footer-center <text>          Centered footer text
      --footer-font-name <name>       Set footer font name (default Arial)
      --footer-font-size <size>       Set footer font size (default 12)
      --footer-html <url>             Adds a html footer
      --footer-left <text>            Left aligned footer text
      --footer-line                   Display line above the footer
      --no-footer-line                Do not display line above the footer
                                      (default)
      --footer-right <text>           Right aligned footer text
      --footer-spacing <real>         Spacing between footer and content in mm
                                      (default 0)
      --header-center <text>          Centered header text
      --header-font-name <name>       Set header font name (default Arial)
      --header-font-size <size>       Set header font size (default 12)
      --header-html <url>             Adds a html header
      --header-left <text>            Left aligned header text
      --header-line                   Display line below the header
      --no-header-line                Do not display line below the header
                                      (default)
      --header-right <text>           Right aligned header text
      --header-spacing <real>         Spacing between header and content in mm
                                      (default 0)
      --replace <name> <value>        Replace [name] with value in header and
                                      footer (repeatable)

also proxy.

**Comment by JazzCore** [comment]
Now you can pass ``custom-header`` in options like this:

    'custom-header' : [
        ('Accept-Encoding', 'gzip')
    ]
