### ISSUE TITLE
Cover and TOC seem to be added in incorrect order.

### ISSUE THREAD

**Issue by bsteverink** [JazzCore/python-pdfkit#55]
In the PDFKit.command method both TOC and cover arguments are added if specified. However when both TOC and cover are specified, TOC is added before cover, resulting in the TOC being rendered on the first page and the cover on the second.

**Comment by JazzCore** [comment]
Fixed in #57. Now you if you want cover before TOC you can pass ``cover_first=True`` argument in PDFKit constructor
