### ISSUE TITLE
wkhtmltopdf support

### ISSUE THREAD

**Issue by vatsalparekh** [JazzCore/python-pdfkit#56]
Hey,
When i was trying to install pdfkit through pip, it gave error of 

` No wkhtmltopdf executable found: "" If this file exists please check that this process can read it. `

So can't i just use it using pip?

More, i installed the wkhtmltopdf using apt-get, but using pdfkit in celery to run multiple asyncronus tasks, it gives error of 
`QXcbConnection: Could not connect to display`
I got that it is not getting xvfb display windows available in server, so any solution which I can solve into python level itself ?

**Comment by JazzCore** [comment]
Yes, you cant just install python module, you need actual wkhtmltopdf binary.

As for error - check this link http://unix.stackexchange.com/a/192646. You will need to compile wkhtmltopdf since precompiled versions in debian repositories does not support headless mode.

**Comment by jakewins** [comment]
For future travelers, the solution recommended by Debian now is to use xvfb. We wrote a subclass of the PDFKit class to achieve that:

    import pdfkit
    
    class HeadlessPdfKit(pdfkit.PDFKit):
        def command(self, path=None):
            return ['xvfb-run', '--'] + super().command(path)
    
    pdf = HeadlessPdfKit("<html></html>", 'string').to_pdf(False)

**Comment by zksfyz** [comment]
@jakewins  Your are right!

**Comment by mrshu** [comment]
For anyone who would appreciate @jakewins' wrapper as a full fledged package, I've put it together here: https://pypi.org/project/headless-pdfkit/

Enjoy!

**Comment by tarun29061990** [comment]
how to pas 'auto_servernum' in headless-pdfkit??

**Comment by mrshu** [comment]
Hey @tarun29061990, you can find a small example in the documentation: http://headless-pdfkit.readthedocs.io/en/latest/#examples
