### ISSUE TITLE
Project still actively maintained?

### ISSUE THREAD

**Issue by woodb** [JazzCore/python-pdfkit#60]
I noticed that the last commit was nearly 2 years ago and there have been PR's sitting for a little while now.

@JazzCore is this project still actively maintained?

Would it make sense to fork this and continue development elsewhere?

**Comment by JazzCore** [comment]
Hi @woodb!

Sorry about that :( I'm kinda lost interest in this project and still trying to find a minute go through issues and PRs, will do this in a few weeks.

If you are really determined to continue development, I can give you collaborator access to this repository, so you can continue here.

**Comment by alanhamlett** [comment]
@JazzCore I would like contributor access to help maintain things. I've helped maintain other open-source Python libraries and am actively invested in keeping python-pdfkit updated since we use it at https://wakatime.com.

**Comment by JazzCore** [comment]
Hey @alanhamlett! Awesome, thanks!

**Comment by alanhamlett** [comment]
@JazzCore thanks, any of these contributors active and could help review PRs?

**Comment by JazzCore** [comment]
No, you're the only one with collaborator access. Just ping me when you want a review, I'll try to look at it. Also ping me when you feel like making a new release at PyPI

**Comment by alanhamlett** [comment]
Thanks, closing this issue.
