### ISSUE TITLE
Header/Footer HTML Path

### ISSUE THREAD

**Issue by gavinr** [JazzCore/python-pdfkit#61]
When using `wkhtmltopdf` in command line, I can specify a local HTML file to use as the footer (or header): 

`wkhtmltopdf --footer-html .\footer.html .\content.html output.pdf`

When I pass that reference in the `options` variable:

`options = {"footer-html":"footer.html"}`

...  PDFKit never works for me. Passing a url (mentioned [here](https://github.com/JazzCore/python-pdfkit/issues/27)) **_does_** work:

`options = {"footer-html":"http://google.com"}`

Two questions:
1. Is it possible to pass a reference to a local HTML file?
2. If so, where does the file need to be relative to? I have tried relative and absolute paths, neither seem to work.

Thanks!

**Comment by arasub** [comment]
@gavinr  To answer your questions:  yes it support local URL  and below is how we have used in our application.

            options = {
                'footer-html':  'http://mydomain.app:82/static/partials/pdffooter.html",
                'footer-right': '[page] of [topage]',
            }

@JazzCore 
I'm working out to figure few more answers like
1. How to specify the footer/header size like i want to use my logo in footer which is of 20*20
2. Page No. not displaying if we use as per https://madalgo.au.dk/%7Ejakobt/wkhtmltoxdoc/wkhtmltopdf-0.9.9-doc.html but when we use as params as above it works fine. 

Thanks 
Arasu.b

**Comment by Jiish** [comment]
@arasub I am facing same issue as @gavinr. I want to use a locally stored .html file in my generated pdf. When calling wkhtmltopdf on command line, I can use  --footer-html file://path/to/file/file.html, but this does not work with pdfkit. I do not want to access the html via URL, but using file:// locally.

**Comment by yafeunteun** [comment]
Using Flask, I've been able to include a footer either by adding a route that renders a footer.html template:


```
@app.route('/footer')                                                                                                                                 
def footer():                                                                                                                                         
    return render_template('pdf_footer.html') 
```

Then in the options: 

`
options = {                                                                                                                                       
        'footer-html': 'http://localhost:5000/footer'                                                                                                 
}   
`

Or without a route, just by specifying the path to the html file: 

`
options = {                                                                                                                                       
        'footer-html': './templates/pdf_footer.html''                                                                                                 
}   
`

Also, in the footer/header html file, you must specify the doctype  -- see https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1593 

Minimal example of the pdf_footer.html: 


```
<!doctype html>                                                                                                                                       
<p>This is the footer</p> 
```

**Comment by xsa** [comment]
Hi All — not sure if this has been resolved yet or not, but I’m still having the same issue as the OP. Can’t include local files (I’m on MacOSX). Thanks.

**Comment by JazzCore** [comment]
Seems working for me, tried with this:

```python
options = {"footer-html":"footer.html"}
pdfkit.from_string('test data', 'out.pdf', options=options, verbose=True)
```

Path handling is done by ``wkhtmltopdf`` but I think that it can handle both relative and absolute path, working directory for it is the same as the directory for python env.

Feel free to reopen, but please provide a reproducible test case
