### ISSUE TITLE
Python3: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by akashpatni** [JazzCore/python-pdfkit#62]
Hi, 

I am facing the below mention error while generating PDF

'str' object has no attribute 'decode' 
at line 40:

self.wkhtmltopdf = self.configuration.wkhtmltopdf.decode('utf-8') 

in pdfkit.py

Here is my code:

config = pdfkit.configuration(wkhtmltopdf='/usr/bin/wkhtmltopdf')
pdfkit.from_url('https://micropyramid.com/blog/how-to-create-pdf-files-in-python-using-pdfkit/', 'micro.pdf', configuration=config)

Any help on this.
Thanks

**Comment by JazzCore** [comment]
I believe that's fixed in #48
