### ISSUE TITLE
Creating PDF from URL grabs mobile version

### ISSUE THREAD

**Issue by lmregus** [JazzCore/python-pdfkit#63]
I have change the page-size in options, but this will only change the size of the actual pdf copy. Have anyone had the same issue?

**Comment by ArthurianX** [comment]
You need a wkhtmltopdf with qt patch http://stackoverflow.com/questions/35617491/how-to-install-wkhtmltopdf-patched-qt-without-compiling

And if you are running headless there's more stuff to do. Use this as a starting point: https://coderwall.com/p/tog9eq/using-wkhtmltopdf-and-an-xvfb-daemon-to-render-html-to-pdf


The idea is that what you got here is related to wkhtmltopdf itself.

I'm having a ton of other problems with the cookies not getting passed properly towards wkhtmltopdf and I've spent the last 3 days debugging this ...

**Comment by JazzCore** [comment]
This looks answered
