### ISSUE TITLE
how to config low quality?

### ISSUE THREAD

**Issue by max-young** [JazzCore/python-pdfkit#67]
here is my code

```
pdf = pdfkit.from_url(url, False)
```

size of the pdf file is too large, time of send to user is too long
so I want change the quality of pdf ,how to config?
I use

```
options = {
      'lowquality': True
  }
```

but error:

```
Error: Failed loading page http://true (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: HostNotFoundError     ] 55%
```

how to do this?thank you

**Comment by apwork** [comment]
Getting the same error here as well. Any ideas for a fix?
`options = {
	'lowquality' : True
}

pdfkit.from_file(htmlfiles, 'merged.pdf', options=options)`

**Comment by riwu** [comment]
> If option without value, use None, False or ” for dict value
So try `'lowquality' : None` instead.

**Comment by JazzCore** [comment]
As mentioned above, try using ``'lowquality': None``

Closing due to date, feel free to reopen if you need ping me about this issue.

Sorry that it took so long for me to get to it...
