### ISSUE TITLE
Input path must be byte string, cannot be unicode string

### ISSUE THREAD

**Issue by hheimbuerger** [JazzCore/python-pdfkit#69]
When using `pdfkit.from_file()`, the `input` parameter must be a byte string. If it's a unicode string, you get an error similar to this:

```
IOError: wkhtmltopdf reported an error:
Error: Failed loading page file::/ (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page file:///E:/ (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page file:///E:/ (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page file:///E:/ (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page file:///E:/ (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page file:///E:/ (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page file:///E:/ (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page file:///E:/ (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page http://o (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page http://o (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page http://o (sometimes it will work just to ignore this error with --load-error-handling ignore)
[…]
```

So you can see right away, somewhere a URI is split into its characters.

The immediate issue is this line ([pdfkit/pdfkit.py:107](https://github.com/JazzCore/python-pdfkit/blob/master/pdfkit/pdfkit.py#L107)):

    if isinstance(self.source.source, str):

Which should be changed to:

    if isinstance(self.source.source, basestring):

This should probably be fixed in a couple more places, I see more occurences of this and `isinstance(x, str)` is almost always not what you want.

**Comment by JazzCore** [comment]
Are you running python 3+? This looks like a compatibility bug, I'll look into this, thanks

**Comment by JazzCore** [comment]
Should be fixed now

**Comment by hheimbuerger** [comment]
Sorry, I should have mentioned this before: no, this refers to Python 2.7, not 3.x. In fact, from my understanding of how unicode works in Python 3, this issue should have only ever occured in Python 2 (but I haven't tested that).

Thanks for implementing the fix!
