### ISSUE TITLE
Number of pages?

### ISSUE THREAD

**Issue by cesarmarroquin** [JazzCore/python-pdfkit#71]
Is there a way to get the number of pages?  I cant find anything in the documentation or code that shows how to retrieve the page count for a generated pdf.

**Comment by arasub** [comment]
This option will give you the page count
            options = {
               'footer-right': '[page] of [topage]',
            }

http://stackoverflow.com/questions/33734792/page-number-in-pdf-converted-from-html-pdfkit-python-django/41726624#41726624

**Comment by Mr-liu-yang** [comment]
In this way, there has a mistake, why? 
![2e5a72c8-e9d9-4e57-b9e6-4936eb55bf7b](https://user-images.githubusercontent.com/31237992/43377323-8ce406a4-93f2-11e8-8cf0-b03dc11abf41.png)

**Comment by JazzCore** [comment]
This seems like a wkhtmltopdf question, no idea how to do it, sorry.

Sorry that it took so long for me to get to it...

**Comment by atishmahadik** [comment]
[arasub](https://github.com/arasub) Thanks it works for me
