### ISSUE TITLE
python pdfkit wkhtmltopdf 0.12.2.4 -> 0.12.3 (with patched qt) - totally different pdf's

### ISSUE THREAD

**Issue by kxgoto1927** [JazzCore/python-pdfkit#73]
Ok, I am using pdfkit in python 3.6. I am using Ubuntu LTS 16.04. I have two virtual environments. One has wkhtmltopdf 0.12.2.4 and one has 0.12.3 (with patched qt). I need the patched qt version because I want to add text to the bottom of the pdf. However, the disparity between the two is really noticeable. The version without the patch is really good, it actually is aligned with what one would see if they visited the website and printed to pdf. I'll attach the two.

[test1.pdf](https://github.com/JazzCore/python-pdfkit/files/705543/test1.pdf)
[test2.pdf](https://github.com/JazzCore/python-pdfkit/files/705544/test2.pdf)

**Comment by JazzCore** [comment]
This is most probably caused by wkhtmltopdf itself, not pdfkit. Try running actual binaries to see if problem persists
