### ISSUE TITLE
pdfkit configuration via meta tags only works with from_string

### ISSUE THREAD

**Issue by beager** [JazzCore/python-pdfkit#74]
In debugging why only certain invocations of pdfkit respect meta tag specification of wkhtmltopdf configuration options, I was able to trace through the code and discover that only `from_string` provides the ability to discover configuration options from meta tags.

This would be nice to have for `from_file` and `from_url` invocations, but in looking at the code, I realize that this might not be trivial to add, and may actually add processing time to be done right.

Barring that, it might be good to note in documentation that meta tag configuration is available only for `from_string` invocations.

Thanks for your consideration, and for building and maintaining such a useful project.

**Comment by mpnowacki** [comment]
I also bumped into that, and had to read the code to understand why my meta tags were not working. A note on that in the Readme would be nice, but I don't understand why these tags should not work with `from_file`.

**Comment by BigNerd95** [comment]
You can solve this problem by using the library in this way
```python
kit = pdfkit.PDFKit(location, "url")
kit.options.update(kit._find_options_in_meta(requests.get(location).text))
res = kit.to_pdf()
```

Alternatively you can modify the library adding this code in the __init__ function of pdfkit.py
```python
        self.options = dict()
        if self.source.isString():
            self.options.update(self._find_options_in_meta(url_or_file))
        elif self.source.isUrl():   # add
            r = requests.get(url_or_file)  # add
            self.options.update(self._find_options_in_meta(r.text))  # add
```

**Comment by edurguti** [comment]
> You can solve this problem by using the library in this way
> 
> ```python
> kit = pdfkit.PDFKit(location, "url")
> kit.options.update(kit._find_options_in_meta(requests.get(location).text))
> res = kit.to_pdf()
> ```
> 
> Alternatively you can modify the library adding this code in the **init** function of pdfkit.py
> 
> ```python
>         self.options = dict()
>         if self.source.isString():
>             self.options.update(self._find_options_in_meta(url_or_file))
>         elif self.source.isUrl():   # add
>             r = requests.get(url_or_file)  # add
>             self.options.update(self._find_options_in_meta(r.text))  # add
> ```

How about using meta tags when generating from file?

**Comment by BigNerd95** [comment]
```python
kit = pdfkit.PDFKit(location, "file")
kit.options.update(kit._find_options_in_meta(open(location, "rt").read()))
res = kit.to_pdf()
```
NOT tested, please confirm if it works

**Comment by JazzCore** [comment]
Sorry, I'll keep it as is because ``wkhtmltopdf`` input source is passed through library only in one case -- ``from_string``. If we are to add this for ``from_file`` or ``from_url`` we would need to firstly read a file or URL, then do meta tags search and only then pass it to ``wkhtmltopdf`` which causes big compications and insane overhead for a niche feature.

Also solutions provided above are absolutely fine and should be working for such cases
