### ISSUE TITLE
--margin-top specified in incorrect location

### ISSUE THREAD

**Issue by toleabivol** [JazzCore/python-pdfkit#78]
Hello , 

I get `--margin-top specified in incorrect location` error with the following options dict :

```
options = {
                    'zoom':'0.64',
                    'dpi':'150',
                    'javascript-delay':'2000',
                    'page-size': 'A4',
                    'margin-top': '0mm',
                    'margin-right': '0mm',
                    'margin-bottom': '0mm',
                    'margin-left': '0mm',
                    'disable-smart-shrinking': '*None',
                    #'encoding': "UTF-8",
                    #'no-outline': None
                }
```

this started when I added `'disable-smart-shrinking': '*None'` . If I shift options up and down it will change from `--margin-top specified in incorrect location` to `--dpi specified in incorrect location`

**Comment by toleabivol** [comment]
Some wrong documentation got me to this issue. So, instead of :
`'disable-smart-shrinking': '*None'`
should be
`'disable-smart-shrinking': None,`

**Comment by grahamcracker** [comment]
For others experiencing this issue - I believe this flag is supposed to passed with no arguments. So with `python-pdfkit`, smart shrinking can be disabled with:

> {
'disable-smart-shrinking': ''
}
