### ISSUE TITLE
Unable to run second X-Server command

### ISSUE THREAD

**Issue by xGlorify** [JazzCore/python-pdfkit#79]
Ubuntu LTS 16.04 - Fresh install, nothing I tried on my first go-round worked, and I ended up ruining my entire install by accidentally changing all the permissions within my /usr/bin folder.

Issue: successfully install pdfkit via pip, and wkhtmltopdf via apt-get.

Then I try and run `echo -e '#!/bin/bash\nxvfb-run -a --server-args="-screen 0, 1024x768x24" /usr/bin/wkhtmltopdf -q $*' > ` and get `-su: /usr/bin/wkhtmltopdf.sh: Permission denied`

Also tried installing via the static binary on the site provided [here.](https://github.com/JazzCore/python-pdfkit/blob/master/travis/before-script.sh)

**Comment by JazzCore** [comment]
You can try a solution posted in #82, closing for now.

Sorry that it took so long for me to get to it...
