### ISSUE TITLE
Different headers for different pages?

### ISSUE THREAD

**Issue by benwad** [JazzCore/python-pdfkit#80]
I noticed that `wkhtmltopdf` allows header files to be specified for each HTML file, so we can have different headers for different sections in the same output document. I guess this would involve specifying different `options` for each of the input files. Is that currently possible in `pdfkit`? I couldn't find it in the documentation or in a quick browse through the source.

**Comment by JazzCore** [comment]
I think that this should work out of the box, since it only needs to be specified in ``wkhtmltopdf`` options. If someone would provide an example command I can test it, and implement it it if fails when ran through pdfkit
