### ISSUE TITLE
Error QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by domzinhuu** [JazzCore/python-pdfkit#82]
I use django v1.11.1, wkhtmltopdf 0.12.2.4 and pdfkit 0.6.1, i think that i have conflict, when i use wkhtmltopdf google.com google.pdf in my terminal this work fine, but when i use in my app i get this error

wkhtmltopdf exited with non-zero code -6. error:
QXcbConnection: Could not connect to display

**Comment by WilliamDenniss** [comment]
Here's a relevant stack exchange question: https://unix.stackexchange.com/q/192642/215718

What I recommend is *don't* use the Debian package. Grab the latest generic linux binary here: https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.4

You'll want either the, `wkhtmltox-0.12.4_linux-generic-amd64.tar.xz` or `wkhtmltox-0/usr/bin/.12.4_linux-generic-i386.tar.xz` download. Then copy the binary from `wkhtmltox/bin` to `/usr/bin/` and you're done. It's also a newer version of wkhtmltopdf to boot.

Or you can use `xvfb` to wrap it as described here https://github.com/JazzCore/python-pdfkit/wiki/Using-wkhtmltopdf-without-X-server#debianubuntu

**Comment by massood** [comment]
The [wrapper script](https://github.com/JazzCore/python-pdfkit/wiki/Using-wkhtmltopdf-without-X-server#debianubuntu) didn't work for me. But the [binary from the GitHub repo](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/) did.

**Comment by slisznia** [comment]
Note about wkhtmltopdf (0.12.4) in Ubuntu 18.04:

```
Reduced Functionality:
  This version of wkhtmltopdf has been compiled against a version of QT without
  the wkhtmltopdf patches. Therefore some features are missing, if you need
  these features please use the static version.

  Currently the list of features only supported with patch QT includes:
 * Running without an X11 server.

```

**Comment by AlexVentura** [comment]
Solution from @WilliamDenniss worked for me!

**Comment by Thornolf** [comment]
Wrapping with `xvfb` worked for me, thanks :)

**Comment by AdityaKannan** [comment]
The solution from @WilliamDenniss works perfectly. Thank you so much.

**Comment by JazzCore** [comment]
Closing since its "fixed". Good idea to update wiki page about running without X server with an alternative binary from https://github.com/wkhtmltopdf/wkhtmltopdf/releases/

Sorry that it took so long for me to get to it...

**Comment by Sherkhan7** [comment]
Solution from @WilliamDenniss worked. Thank you ;) I tested on ubuntu 18.04
