### ISSUE TITLE
css option not working

### ISSUE THREAD

**Issue by zahidmak** [JazzCore/python-pdfkit#93]
I am trying to style the html using css file but I don't it being applied to the output pdf.

```
options = {
    'page-size': 'Letter',
    'margin-top': '0.75in',
    'margin-right': '0.75in',
    'margin-bottom': '0.75in',
    'margin-left': '0.75in',
    'encoding': "UTF-8",
    'no-outline': None
}
css = 'mystyle.css'
pdfkit.from_string(body, 'out.pdf', options=options, css=css)
```

Please suggest if you have any workaround to this.

Thank you,

**Comment by categulario** [comment]
Did you try first passing `'user-style-sheet'` in the `options` dictionary?

**Comment by Swiftkilla** [comment]
> Did you try first passing 'user-style-sheet' in the options dictionary?

I'm facing a similar issue, I would like to customise the style of the PDF. I will say that if you are able to style the web page the exact way you want the PDF to be styled (unfortunately not in my case), then out-of-the-box pdfkit is absolutely perfect pretty much. I could suggest that it would be nice to see "smart-auto" page breaks (don't put two halves of a picture on 2 pages).

I digress, neither of the following work:
`css='<path\\to\\css>'
pdfkit.from_url('<url_to_export>', '<out\\file\\path\\name>.pdf', options=options, css=css)`

OR

`options = {
  'page-size': 'A4',
  'margin-top': '0.0in',
  'margin-right': '0.0in',
  'margin-bottom': '0.0in',
  'margin-left': '0.0in',
  'encoding': "UTF-8",
  'cookie': [('cookie_name', 'cookie_val')],
  'no-outline': None,
  'user-style-sheet': '<path_to_css>'
}`

Is there something obvious that I'm doing wrong here?

TYIA

**Comment by Swiftkilla** [comment]
Update:
If you cannot make the stylesheet work, then try to add it during the processing.
For example;
If you are sending plain HTML data, like so -
```
<div>This is some content</div>
<div>
  <ul>
    <li>
      This is an unordered list
    </li>
  </ul>
</div>
```

Then in this case specifically, there is a workaround like so -
1) Append some CSS data to the beginning of your HTML data i.e.
```
<style>
div {
    display: none;
}
</style>
```
In doing so, the HTML style is read as part of the HTML file (or string).

Hope this helps @zahidmak

**Comment by JazzCore** [comment]
Closing due to date, feel free to reopen if you need ping me about this issue.

In any case, please try running wkhtmltopdf from CLI to see whether it produces same issue. You can do it something like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```

Sorry that it took so long for me to get to it...
