### ISSUE TITLE
Material Icons are not render correctly

### ISSUE THREAD

**Issue by quytang** [JazzCore/python-pdfkit#96]
Hi there,
I need to render a page to PDF file which includes Material icons but it doesn't seem to work.

**templates/pdf.html**
```
<html>

<head>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

  <style>
    * {
      font-family: Roboto, Helvetica, sans-serif;
    }
</style>
</head>
<body>
  Just test 
  <i class="material-icons">remove_red_eye</i>
</body>
</html>

```

**gen.py**
```
import pdfkit
from django.template.loader import render_to_string

html = render_to_string('pdf.html')
pdfkit.from_string(html, 'out.pdf')

```

`out.pdf` only contains the text `Just test`. Are there any chance to fix it?

** Question on SO - [question](https://stackoverflow.com/questions/49210369/convert-html-to-pdf-with-material-icons-in-python-using-pdfkit)

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result.

You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```

Sorry that it took so long for me to get to it...
